
package com.fedex.ws.uploaddocument.v17;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UploadDocumentService", targetNamespace = "http://fedex.com/ws/uploaddocument/v17", wsdlLocation = "ws/fedex/wsdl/UploadDocumentService_v17.wsdl")
public class UploadDocumentService
    extends Service
{

    private final static URL UPLOADDOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPLOADDOCUMENTSERVICE_EXCEPTION;
    private final static QName UPLOADDOCUMENTSERVICE_QNAME = new QName("http://fedex.com/ws/uploaddocument/v17", "UploadDocumentService");

    static {
        UPLOADDOCUMENTSERVICE_WSDL_LOCATION = com.fedex.ws.uploaddocument.v17.UploadDocumentService.class.getResource("ws/fedex/wsdl/UploadDocumentService_v17.wsdl");
        WebServiceException e = null;
        if (UPLOADDOCUMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/UploadDocumentService_v17.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        UPLOADDOCUMENTSERVICE_EXCEPTION = e;
    }

    public UploadDocumentService() {
        super(__getWsdlLocation(), UPLOADDOCUMENTSERVICE_QNAME);
    }

    public UploadDocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADDOCUMENTSERVICE_QNAME, features);
    }

    public UploadDocumentService(URL wsdlLocation) {
        super(wsdlLocation, UPLOADDOCUMENTSERVICE_QNAME);
    }

    public UploadDocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADDOCUMENTSERVICE_QNAME, features);
    }

    public UploadDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UploadDocumentPortType
     */
    @WebEndpoint(name = "UploadDocumentServicePort")
    public UploadDocumentPortType getUploadDocumentServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/uploaddocument/v17", "UploadDocumentServicePort"), UploadDocumentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadDocumentPortType
     */
    @WebEndpoint(name = "UploadDocumentServicePort")
    public UploadDocumentPortType getUploadDocumentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/uploaddocument/v17", "UploadDocumentServicePort"), UploadDocumentPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADDOCUMENTSERVICE_EXCEPTION!= null) {
            throw UPLOADDOCUMENTSERVICE_EXCEPTION;
        }
        return UPLOADDOCUMENTSERVICE_WSDL_LOCATION;
    }

}
