
package com.fedex.ws.uploaddocument.v17;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "UploadDocumentServicePort", serviceName = "UploadDocumentService", targetNamespace = "http://fedex.com/ws/uploaddocument/v17", wsdlLocation = "ws/fedex/wsdl/UploadDocumentService_v17.wsdl", endpointInterface = "com.fedex.ws.uploaddocument.v17.UploadDocumentPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class UploadDocumentService_UploadDocumentServicePortImpl
    implements UploadDocumentPortType
{


    public UploadDocumentService_UploadDocumentServicePortImpl() {
    }

    /**
     * 
     * @param uploadDocumentsRequest
     * @return
     *     returns com.fedex.ws.uploaddocument.v17.UploadDocumentsReply
     */
    public UploadDocumentsReply uploadDocuments(UploadDocumentsRequest uploadDocumentsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param uploadImagesRequest
     * @return
     *     returns com.fedex.ws.uploaddocument.v17.UploadImagesReply
     */
    public UploadImagesReply uploadImages(UploadImagesRequest uploadImagesRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param uploadDocumentsWithShipmentDataRequest
     * @return
     *     returns com.fedex.ws.uploaddocument.v17.UploadDocumentsWithShipmentDataReply
     */
    public UploadDocumentsWithShipmentDataReply uploadDocumentsWithShipmentData(UploadDocumentsWithShipmentDataRequest uploadDocumentsWithShipmentDataRequest) {
        //replace with your impl here
        return null;
    }

}
