
package com.ups.wsdl.xoltws.paperlessdocumentapi.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PaperlessDocumentAPIService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/PaperlessDocumentAPI/v1.0", wsdlLocation = "ws/ups/wsdl/PaperlessDocumentAPI.wsdl")
public class PaperlessDocumentAPIService
    extends Service
{

    private final static URL PAPERLESSDOCUMENTAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException PAPERLESSDOCUMENTAPISERVICE_EXCEPTION;
    private final static QName PAPERLESSDOCUMENTAPISERVICE_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/PaperlessDocumentAPI/v1.0", "PaperlessDocumentAPIService");

    static {
        PAPERLESSDOCUMENTAPISERVICE_WSDL_LOCATION = com.ups.wsdl.xoltws.paperlessdocumentapi.v1.PaperlessDocumentAPIService.class.getResource("ws/ups/wsdl/PaperlessDocumentAPI.wsdl");
        WebServiceException e = null;
        if (PAPERLESSDOCUMENTAPISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/PaperlessDocumentAPI.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PAPERLESSDOCUMENTAPISERVICE_EXCEPTION = e;
    }

    public PaperlessDocumentAPIService() {
        super(__getWsdlLocation(), PAPERLESSDOCUMENTAPISERVICE_QNAME);
    }

    public PaperlessDocumentAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAPERLESSDOCUMENTAPISERVICE_QNAME, features);
    }

    public PaperlessDocumentAPIService(URL wsdlLocation) {
        super(wsdlLocation, PAPERLESSDOCUMENTAPISERVICE_QNAME);
    }

    public PaperlessDocumentAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAPERLESSDOCUMENTAPISERVICE_QNAME, features);
    }

    public PaperlessDocumentAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaperlessDocumentAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaperlessDocumentAPIPortType
     */
    @WebEndpoint(name = "PaperlessDocumentAPIPort")
    public PaperlessDocumentAPIPortType getPaperlessDocumentAPIPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/PaperlessDocumentAPI/v1.0", "PaperlessDocumentAPIPort"), PaperlessDocumentAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaperlessDocumentAPIPortType
     */
    @WebEndpoint(name = "PaperlessDocumentAPIPort")
    public PaperlessDocumentAPIPortType getPaperlessDocumentAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/PaperlessDocumentAPI/v1.0", "PaperlessDocumentAPIPort"), PaperlessDocumentAPIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAPERLESSDOCUMENTAPISERVICE_EXCEPTION!= null) {
            throw PAPERLESSDOCUMENTAPISERVICE_EXCEPTION;
        }
        return PAPERLESSDOCUMENTAPISERVICE_WSDL_LOCATION;
    }

}
