
package com.ups.wsdl.xoltws.lbrecovery.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LBRecovery", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0", wsdlLocation = "ws/ups/wsdl/LabelRecoveryWS.wsdl")
public class LBRecovery
    extends Service
{

    private final static URL LBRECOVERY_WSDL_LOCATION;
    private final static WebServiceException LBRECOVERY_EXCEPTION;
    private final static QName LBRECOVERY_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0", "LBRecovery");

    static {
        LBRECOVERY_WSDL_LOCATION = com.ups.wsdl.xoltws.lbrecovery.v1.LBRecovery.class.getResource("ws/ups/wsdl/LabelRecoveryWS.wsdl");
        WebServiceException e = null;
        if (LBRECOVERY_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/LabelRecoveryWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        LBRECOVERY_EXCEPTION = e;
    }

    public LBRecovery() {
        super(__getWsdlLocation(), LBRECOVERY_QNAME);
    }

    public LBRecovery(WebServiceFeature... features) {
        super(__getWsdlLocation(), LBRECOVERY_QNAME, features);
    }

    public LBRecovery(URL wsdlLocation) {
        super(wsdlLocation, LBRECOVERY_QNAME);
    }

    public LBRecovery(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LBRECOVERY_QNAME, features);
    }

    public LBRecovery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBRecovery(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "Port")
    public PortType getPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0", "Port"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "Port")
    public PortType getPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0", "Port"), PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LBRECOVERY_EXCEPTION!= null) {
            throw LBRECOVERY_EXCEPTION;
        }
        return LBRECOVERY_WSDL_LOCATION;
    }

}
