
package com.ups.wsdl.xoltws.lbrecovery.v1;

import com.ups.xmlschema.xoltws.lbrecovery.v1.LabelRecoveryRequest;
import com.ups.xmlschema.xoltws.lbrecovery.v1.LabelRecoveryResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.lbrecovery.v1.ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.lbrecovery.v1.LabelRecoveryResponse
     * @throws LabelRecoveryErrorMessage
     */
    @WebMethod(operationName = "ProcessLabelRecovery", action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.1")
    @WebResult(name = "LabelRecoveryResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0", partName = "Body")
    public LabelRecoveryResponse processLabelRecovery(
        @WebParam(name = "LabelRecoveryRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0", partName = "Body")
        LabelRecoveryRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws LabelRecoveryErrorMessage
    ;

}
