
package com.ups.wsdl.xoltws.freightship.v1;

import com.ups.xmlschema.xoltws.freightship.v1.FreightShipRequest;
import com.ups.xmlschema.xoltws.freightship.v1.FreightShipResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "FreightShipPort", serviceName = "FreightShipService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", wsdlLocation = "ws/ups/wsdl/FreightShip.wsdl", endpointInterface = "com.ups.wsdl.xoltws.freightship.v1.FreightShipPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class FreightShipService_FreightShipPortImpl
    implements FreightShipPortType
{


    public FreightShipService_FreightShipPortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.freightship.v1.FreightShipResponse
     * @throws ShipErrorMessage
     */
    public FreightShipResponse processShipment(FreightShipRequest body, UPSSecurity upsSecurity)
        throws ShipErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
