
package com.ups.wsdl.xoltws.freightship.v1;

import com.ups.xmlschema.xoltws.freightship.v1.FreightShipRequest;
import com.ups.xmlschema.xoltws.freightship.v1.FreightShipResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FreightShipPortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws._if.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.freightship.v1.ObjectFactory.class
})
public interface FreightShipPortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.freightship.v1.FreightShipResponse
     * @throws ShipErrorMessage
     */
    @WebMethod(operationName = "ProcessShipment", action = "http://onlinetools.ups.com/webservices/FreightShipBinding/v1.0")
    @WebResult(name = "FreightShipResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0", partName = "Body")
    public FreightShipResponse processShipment(
        @WebParam(name = "FreightShipRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0", partName = "Body")
        FreightShipRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws ShipErrorMessage
    ;

}
