
package com.ups.wsdl.xoltws.freightship.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FreightShipService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", wsdlLocation = "ws/ups/wsdl/FreightShip.wsdl")
public class FreightShipService
    extends Service
{

    private final static URL FREIGHTSHIPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FREIGHTSHIPSERVICE_EXCEPTION;
    private final static QName FREIGHTSHIPSERVICE_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", "FreightShipService");

    static {
        FREIGHTSHIPSERVICE_WSDL_LOCATION = com.ups.wsdl.xoltws.freightship.v1.FreightShipService.class.getResource("ws/ups/wsdl/FreightShip.wsdl");
        WebServiceException e = null;
        if (FREIGHTSHIPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/FreightShip.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FREIGHTSHIPSERVICE_EXCEPTION = e;
    }

    public FreightShipService() {
        super(__getWsdlLocation(), FREIGHTSHIPSERVICE_QNAME);
    }

    public FreightShipService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FREIGHTSHIPSERVICE_QNAME, features);
    }

    public FreightShipService(URL wsdlLocation) {
        super(wsdlLocation, FREIGHTSHIPSERVICE_QNAME);
    }

    public FreightShipService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FREIGHTSHIPSERVICE_QNAME, features);
    }

    public FreightShipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreightShipService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FreightShipPortType
     */
    @WebEndpoint(name = "FreightShipPort")
    public FreightShipPortType getFreightShipPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", "FreightShipPort"), FreightShipPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FreightShipPortType
     */
    @WebEndpoint(name = "FreightShipPort")
    public FreightShipPortType getFreightShipPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", "FreightShipPort"), FreightShipPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FREIGHTSHIPSERVICE_EXCEPTION!= null) {
            throw FREIGHTSHIPSERVICE_EXCEPTION;
        }
        return FREIGHTSHIPSERVICE_WSDL_LOCATION;
    }

}
