
package com.fedex.ws.vacs.v14;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "ValidationAvailabilityAndCommitmentServicePort", serviceName = "ValidationAvailabilityAndCommitmentService", targetNamespace = "http://fedex.com/ws/vacs/v14", wsdlLocation = "ws/fedex/wsdl/ValidationAvailabilityAndCommitmentService_v14.wsdl", endpointInterface = "com.fedex.ws.vacs.v14.ValidationAvailabilityAndCommitmentPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ValidationAvailabilityAndCommitmentService_ValidationAvailabilityAndCommitmentServicePortImpl
    implements ValidationAvailabilityAndCommitmentPortType
{


    public ValidationAvailabilityAndCommitmentService_ValidationAvailabilityAndCommitmentServicePortImpl() {
    }

    /**
     * 
     * @param getAllServicesAndPackagingRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.GetAllServicesAndPackagingReply
     */
    public GetAllServicesAndPackagingReply getAllServicesAndPackaging(GetAllServicesAndPackagingRequest getAllServicesAndPackagingRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getAllSpecialServicesRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.GetAllSpecialServicesReply
     */
    public GetAllSpecialServicesReply getAllSpecialServices(GetAllSpecialServicesRequest getAllSpecialServicesRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param serviceAvailabilityRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.ServiceAvailabilityReply
     */
    public ServiceAvailabilityReply serviceAvailability(ServiceAvailabilityRequest serviceAvailabilityRequest) {
        //replace with your impl here
        return null;
    }

}
