
package com.fedex.ws.vacs.v14;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ValidationAvailabilityAndCommitmentService", targetNamespace = "http://fedex.com/ws/vacs/v14", wsdlLocation = "ws/fedex/wsdl/ValidationAvailabilityAndCommitmentService_v14.wsdl")
public class ValidationAvailabilityAndCommitmentService
    extends Service
{

    private final static URL VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_EXCEPTION;
    private final static QName VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_QNAME = new QName("http://fedex.com/ws/vacs/v14", "ValidationAvailabilityAndCommitmentService");

    static {
        VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_WSDL_LOCATION = com.fedex.ws.vacs.v14.ValidationAvailabilityAndCommitmentService.class.getResource("ws/fedex/wsdl/ValidationAvailabilityAndCommitmentService_v14.wsdl");
        WebServiceException e = null;
        if (VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/ValidationAvailabilityAndCommitmentService_v14.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_EXCEPTION = e;
    }

    public ValidationAvailabilityAndCommitmentService() {
        super(__getWsdlLocation(), VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_QNAME);
    }

    public ValidationAvailabilityAndCommitmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_QNAME, features);
    }

    public ValidationAvailabilityAndCommitmentService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_QNAME);
    }

    public ValidationAvailabilityAndCommitmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_QNAME, features);
    }

    public ValidationAvailabilityAndCommitmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidationAvailabilityAndCommitmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidationAvailabilityAndCommitmentPortType
     */
    @WebEndpoint(name = "ValidationAvailabilityAndCommitmentServicePort")
    public ValidationAvailabilityAndCommitmentPortType getValidationAvailabilityAndCommitmentServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/vacs/v14", "ValidationAvailabilityAndCommitmentServicePort"), ValidationAvailabilityAndCommitmentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidationAvailabilityAndCommitmentPortType
     */
    @WebEndpoint(name = "ValidationAvailabilityAndCommitmentServicePort")
    public ValidationAvailabilityAndCommitmentPortType getValidationAvailabilityAndCommitmentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/vacs/v14", "ValidationAvailabilityAndCommitmentServicePort"), ValidationAvailabilityAndCommitmentPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_EXCEPTION!= null) {
            throw VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_EXCEPTION;
        }
        return VALIDATIONAVAILABILITYANDCOMMITMENTSERVICE_WSDL_LOCATION;
    }

}
