
package com.fedex.ws.vacs.v14;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ValidationAvailabilityAndCommitmentPortType", targetNamespace = "http://fedex.com/ws/vacs/v14")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidationAvailabilityAndCommitmentPortType {


    /**
     * 
     * @param getAllServicesAndPackagingRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.GetAllServicesAndPackagingReply
     */
    @WebMethod(action = "http://fedex.com/ws/vacs/v14/getAllServicesAndPackaging")
    @WebResult(name = "GetAllServicesAndPackagingReply", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "GetAllServicesAndPackagingReply")
    public GetAllServicesAndPackagingReply getAllServicesAndPackaging(
        @WebParam(name = "GetAllServicesAndPackagingRequest", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "GetAllServicesAndPackagingRequest")
        GetAllServicesAndPackagingRequest getAllServicesAndPackagingRequest);

    /**
     * 
     * @param getAllSpecialServicesRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.GetAllSpecialServicesReply
     */
    @WebMethod(action = "http://fedex.com/ws/vacs/v14/getAllSpecialServices")
    @WebResult(name = "GetAllSpecialServicesReply", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "GetAllSpecialServicesReply")
    public GetAllSpecialServicesReply getAllSpecialServices(
        @WebParam(name = "GetAllSpecialServicesRequest", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "GetAllSpecialServicesRequest")
        GetAllSpecialServicesRequest getAllSpecialServicesRequest);

    /**
     * 
     * @param serviceAvailabilityRequest
     * @return
     *     returns com.fedex.ws.vacs.v14.ServiceAvailabilityReply
     */
    @WebMethod(action = "http://fedex.com/ws/vacs/v14/serviceAvailability")
    @WebResult(name = "ServiceAvailabilityReply", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "ServiceAvailabilityReply")
    public ServiceAvailabilityReply serviceAvailability(
        @WebParam(name = "ServiceAvailabilityRequest", targetNamespace = "http://fedex.com/ws/vacs/v14", partName = "ServiceAvailabilityRequest")
        ServiceAvailabilityRequest serviceAvailabilityRequest);

}
