
package com.fedex.ws.ship.v26;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "ShipServicePort", serviceName = "ShipService", targetNamespace = "http://fedex.com/ws/ship/v26", wsdlLocation = "ws/fedex/wsdl/ShipService_v26.wsdl", endpointInterface = "com.fedex.ws.ship.v26.ShipPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ShipService_ShipServicePortImpl
    implements ShipPortType
{


    public ShipService_ShipServicePortImpl() {
    }

    /**
     * 
     * @param processTagRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ProcessTagReply
     */
    public ProcessTagReply processTag(ProcessTagRequest processTagRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param processShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ProcessShipmentReply
     */
    public ProcessShipmentReply processShipment(ProcessShipmentRequest processShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deleteTagRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    public ShipmentReply deleteTag(DeleteTagRequest deleteTagRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    public ShipmentReply deleteShipment(DeleteShipmentRequest deleteShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param validateShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    public ShipmentReply validateShipment(ValidateShipmentRequest validateShipmentRequest) {
        //replace with your impl here
        return null;
    }

}
