
package com.fedex.ws.ship.v26;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ShipPortType", targetNamespace = "http://fedex.com/ws/ship/v26")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipPortType {


    /**
     * 
     * @param processTagRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ProcessTagReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v26/processTag")
    @WebResult(name = "ProcessTagReply", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ProcessTagReply")
    public ProcessTagReply processTag(
        @WebParam(name = "ProcessTagRequest", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ProcessTagRequest")
        ProcessTagRequest processTagRequest);

    /**
     * 
     * @param processShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ProcessShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v26/processShipment")
    @WebResult(name = "ProcessShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ProcessShipmentReply")
    public ProcessShipmentReply processShipment(
        @WebParam(name = "ProcessShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ProcessShipmentRequest")
        ProcessShipmentRequest processShipmentRequest);

    /**
     * 
     * @param deleteTagRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v26/deleteTag")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ShipmentReply")
    public ShipmentReply deleteTag(
        @WebParam(name = "DeleteTagRequest", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "DeleteTagRequest")
        DeleteTagRequest deleteTagRequest);

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v26/deleteShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ShipmentReply")
    public ShipmentReply deleteShipment(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest);

    /**
     * 
     * @param validateShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v26.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v26/validateShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ShipmentReply")
    public ShipmentReply validateShipment(
        @WebParam(name = "ValidateShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v26", partName = "ValidateShipmentRequest")
        ValidateShipmentRequest validateShipmentRequest);

}
