
package com.fedex.ws.addressvalidation.v4;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "AddressValidationServicePort", serviceName = "AddressValidationService", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", wsdlLocation = "ws/fedex/wsdl/AddressValidationService_v4.wsdl", endpointInterface = "com.fedex.ws.addressvalidation.v4.AddressValidationPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class AddressValidationService_AddressValidationServicePortImpl
    implements AddressValidationPortType
{


    public AddressValidationService_AddressValidationServicePortImpl() {
    }

    /**
     * 
     * @param addressValidationRequest
     * @return
     *     returns com.fedex.ws.addressvalidation.v4.AddressValidationReply
     */
    public AddressValidationReply addressValidation(AddressValidationRequest addressValidationRequest) {
        //replace with your impl here
        return null;
    }

}
