
package com.fedex.ws.addressvalidation.v4;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AddressValidationService", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", wsdlLocation = "ws/fedex/wsdl/AddressValidationService_v4.wsdl")
public class AddressValidationService
    extends Service
{

    private final static URL ADDRESSVALIDATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDRESSVALIDATIONSERVICE_EXCEPTION;
    private final static QName ADDRESSVALIDATIONSERVICE_QNAME = new QName("http://fedex.com/ws/addressvalidation/v4", "AddressValidationService");

    static {
        ADDRESSVALIDATIONSERVICE_WSDL_LOCATION = com.fedex.ws.addressvalidation.v4.AddressValidationService.class.getResource("ws/fedex/wsdl/AddressValidationService_v4.wsdl");
        WebServiceException e = null;
        if (ADDRESSVALIDATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/AddressValidationService_v4.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ADDRESSVALIDATIONSERVICE_EXCEPTION = e;
    }

    public AddressValidationService() {
        super(__getWsdlLocation(), ADDRESSVALIDATIONSERVICE_QNAME);
    }

    public AddressValidationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDRESSVALIDATIONSERVICE_QNAME, features);
    }

    public AddressValidationService(URL wsdlLocation) {
        super(wsdlLocation, ADDRESSVALIDATIONSERVICE_QNAME);
    }

    public AddressValidationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDRESSVALIDATIONSERVICE_QNAME, features);
    }

    public AddressValidationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressValidationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressValidationPortType
     */
    @WebEndpoint(name = "AddressValidationServicePort")
    public AddressValidationPortType getAddressValidationServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/addressvalidation/v4", "AddressValidationServicePort"), AddressValidationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressValidationPortType
     */
    @WebEndpoint(name = "AddressValidationServicePort")
    public AddressValidationPortType getAddressValidationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/addressvalidation/v4", "AddressValidationServicePort"), AddressValidationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSVALIDATIONSERVICE_EXCEPTION!= null) {
            throw ADDRESSVALIDATIONSERVICE_EXCEPTION;
        }
        return ADDRESSVALIDATIONSERVICE_WSDL_LOCATION;
    }

}
