
package com.fedex.ws.addressvalidation.v4;

import java.util.concurrent.Future;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AddressValidationPortType", targetNamespace = "http://fedex.com/ws/addressvalidation/v4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressValidationPortType {


    /**
     * 
     * @param addressValidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.addressvalidation.v4.AddressValidationReply>
     */
    @WebMethod(operationName = "addressValidation", action = "http://fedex.com/ws/addressvalidation/v4/addressValidation")
    public Response<AddressValidationReply> addressValidationAsync(
        @WebParam(name = "AddressValidationRequest", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", partName = "AddressValidationRequest")
        AddressValidationRequest addressValidationRequest);

    /**
     * 
     * @param asyncHandler
     * @param addressValidationRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "addressValidation", action = "http://fedex.com/ws/addressvalidation/v4/addressValidation")
    public Future<?> addressValidationAsync(
        @WebParam(name = "AddressValidationRequest", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", partName = "AddressValidationRequest")
        AddressValidationRequest addressValidationRequest,
        @WebParam(name = "addressValidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AddressValidationReply> asyncHandler);

    /**
     * 
     * @param addressValidationRequest
     * @return
     *     returns com.fedex.ws.addressvalidation.v4.AddressValidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/addressvalidation/v4/addressValidation")
    @WebResult(name = "AddressValidationReply", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", partName = "AddressValidationReply")
    public AddressValidationReply addressValidation(
        @WebParam(name = "AddressValidationRequest", targetNamespace = "http://fedex.com/ws/addressvalidation/v4", partName = "AddressValidationRequest")
        AddressValidationRequest addressValidationRequest);

}
