
package com.ups.wsdl.xoltws.rate.v1;

import com.ups.xmlschema.xoltws.rate.v1.RateRequest;
import com.ups.xmlschema.xoltws.rate.v1.RateResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "RatePort", serviceName = "RateService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Rate/v1.1", wsdlLocation = "ws/ups/wsdl/RateWS.wsdl", endpointInterface = "com.ups.wsdl.xoltws.rate.v1.RatePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class RateService_RatePortImpl
    implements RatePortType
{


    public RateService_RatePortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.rate.v1.RateResponse
     * @throws RateErrorMessage
     */
    public RateResponse processRate(RateRequest body, UPSSecurity upsSecurity)
        throws RateErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
