
package com.fedex.ws.locs.v12;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "LocationsServicePort", serviceName = "LocationsService", targetNamespace = "http://fedex.com/ws/locs/v12", wsdlLocation = "ws/fedex/wsdl/LocationsService_v12.wsdl", endpointInterface = "com.fedex.ws.locs.v12.LocationsPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class LocationsService_LocationsServicePortImpl
    implements LocationsPortType
{


    public LocationsService_LocationsServicePortImpl() {
    }

    /**
     * 
     * @param searchLocationsRequest
     * @return
     *     returns com.fedex.ws.locs.v12.SearchLocationsReply
     */
    public SearchLocationsReply searchLocations(SearchLocationsRequest searchLocationsRequest) {
        //replace with your impl here
        return null;
    }

}
