
package com.fedex.ws.locs.v12;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LocationsService", targetNamespace = "http://fedex.com/ws/locs/v12", wsdlLocation = "ws/fedex/wsdl/LocationsService_v12.wsdl")
public class LocationsService
    extends Service
{

    private final static URL LOCATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONSSERVICE_EXCEPTION;
    private final static QName LOCATIONSSERVICE_QNAME = new QName("http://fedex.com/ws/locs/v12", "LocationsService");

    static {
        LOCATIONSSERVICE_WSDL_LOCATION = com.fedex.ws.locs.v12.LocationsService.class.getResource("ws/fedex/wsdl/LocationsService_v12.wsdl");
        WebServiceException e = null;
        if (LOCATIONSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/LocationsService_v12.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        LOCATIONSSERVICE_EXCEPTION = e;
    }

    public LocationsService() {
        super(__getWsdlLocation(), LOCATIONSSERVICE_QNAME);
    }

    public LocationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONSSERVICE_QNAME, features);
    }

    public LocationsService(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONSSERVICE_QNAME);
    }

    public LocationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONSSERVICE_QNAME, features);
    }

    public LocationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationsPortType
     */
    @WebEndpoint(name = "LocationsServicePort")
    public LocationsPortType getLocationsServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/locs/v12", "LocationsServicePort"), LocationsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationsPortType
     */
    @WebEndpoint(name = "LocationsServicePort")
    public LocationsPortType getLocationsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/locs/v12", "LocationsServicePort"), LocationsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONSSERVICE_EXCEPTION!= null) {
            throw LOCATIONSSERVICE_EXCEPTION;
        }
        return LOCATIONSSERVICE_WSDL_LOCATION;
    }

}
