
package com.ups.schema.xpci._1_0.lc;

import com.ups.schema.xpci._1_0.error.Errors;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "Errors", targetNamespace = "http://www.ups.com/schema/xpci/1.0/error")
public class Error
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Errors faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Error(String message, Errors faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Error(String message, Errors faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ups.schema.xpci._1_0.error.Errors
     */
    public Errors getFaultInfo() {
        return faultInfo;
    }

}
