
package com.ups.schema.xpci._1_0.lc;

import com.ups.schema.xpci._1_0.auth.AccessRequest;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "LCRequestPortTypePort", serviceName = "LC", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc", wsdlLocation = "ws/ups/wsdl/LandedCost.wsdl", endpointInterface = "com.ups.schema.xpci._1_0.lc.LCRequestPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class LC_LCRequestPortTypePortImpl
    implements LCRequestPortType
{


    public LC_LCRequestPortTypePortImpl() {
    }

    /**
     * 
     * @param accessRequest
     * @param body
     * @return
     *     returns com.ups.schema.xpci._1_0.lc.LandedCostResponse
     * @throws Error
     */
    public LandedCostResponse processLCRequest(LandedCostRequest body, AccessRequest accessRequest)
        throws Error
    {
        //replace with your impl here
        return null;
    }

}
