
package com.ups.schema.xpci._1_0.lc;

import java.util.concurrent.Future;
import com.ups.schema.xpci._1_0.auth.AccessRequest;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LCRequestPortType", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.schema.xpci._1_0.lc.ObjectFactory.class,
    com.ups.schema.xpci._1_0.auth.ObjectFactory.class,
    com.ups.schema.xpci._1_0.error.ObjectFactory.class
})
public interface LCRequestPortType {


    /**
     * 
     * @param accessRequest
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.schema.xpci._1_0.lc.LandedCostResponse>
     */
    @WebMethod(operationName = "ProcessLCRequest", action = "http://www.ups.com/webservices/LCRequestBinding")
    public Response<LandedCostResponse> processLCRequestAsync(
        @WebParam(name = "LandedCostRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc", partName = "Body")
        LandedCostRequest body,
        @WebParam(name = "AccessRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/auth", header = true, partName = "AccessRequest")
        AccessRequest accessRequest);

    /**
     * 
     * @param accessRequest
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessLCRequest", action = "http://www.ups.com/webservices/LCRequestBinding")
    public Future<?> processLCRequestAsync(
        @WebParam(name = "LandedCostRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc", partName = "Body")
        LandedCostRequest body,
        @WebParam(name = "AccessRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/auth", header = true, partName = "AccessRequest")
        AccessRequest accessRequest,
        @WebParam(name = "ProcessLCRequestResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<LandedCostResponse> asyncHandler);

    /**
     * 
     * @param accessRequest
     * @param body
     * @return
     *     returns com.ups.schema.xpci._1_0.lc.LandedCostResponse
     * @throws Error
     */
    @WebMethod(operationName = "ProcessLCRequest", action = "http://www.ups.com/webservices/LCRequestBinding")
    @WebResult(name = "LandedCostResponse", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc", partName = "Body")
    public LandedCostResponse processLCRequest(
        @WebParam(name = "LandedCostRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/lc", partName = "Body")
        LandedCostRequest body,
        @WebParam(name = "AccessRequest", targetNamespace = "http://www.ups.com/schema/xpci/1.0/auth", header = true, partName = "AccessRequest")
        AccessRequest accessRequest)
        throws Error
    ;

}
