
package com.fedex.ws.rate.v28;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "RatePortType", targetNamespace = "http://fedex.com/ws/rate/v28")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RatePortType {


    /**
     * 
     * @param rateRequest
     * @return
     *     returns com.fedex.ws.rate.v28.RateReply
     */
    @WebMethod(action = "http://fedex.com/ws/rate/v28/getRates")
    @WebResult(name = "RateReply", targetNamespace = "http://fedex.com/ws/rate/v28", partName = "RateReply")
    public RateReply getRates(
        @WebParam(name = "RateRequest", targetNamespace = "http://fedex.com/ws/rate/v28", partName = "RateRequest")
        RateRequest rateRequest);

}
