
package com.fedex.ws.cnty.v8;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "CountryServicePort", serviceName = "CountryService", targetNamespace = "http://fedex.com/ws/cnty/v8", wsdlLocation = "ws/fedex/wsdl/CountryService_v8.wsdl", endpointInterface = "com.fedex.ws.cnty.v8.CountryPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class CountryService_CountryServicePortImpl
    implements CountryPortType
{


    public CountryService_CountryServicePortImpl() {
    }

    /**
     * 
     * @param validatePostalRequest
     * @return
     *     returns com.fedex.ws.cnty.v8.ValidatePostalReply
     */
    public ValidatePostalReply validatePostal(ValidatePostalRequest validatePostalRequest) {
        //replace with your impl here
        return null;
    }

}
