
package com.fedex.ws.cnty.v8;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CountryPortType", targetNamespace = "http://fedex.com/ws/cnty/v8")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryPortType {


    /**
     * 
     * @param validatePostalRequest
     * @return
     *     returns com.fedex.ws.cnty.v8.ValidatePostalReply
     */
    @WebMethod(action = "http://fedex.com/ws/cnty/v8/validatePostal")
    @WebResult(name = "ValidatePostalReply", targetNamespace = "http://fedex.com/ws/cnty/v8", partName = "ValidatePostalReply")
    public ValidatePostalReply validatePostal(
        @WebParam(name = "ValidatePostalRequest", targetNamespace = "http://fedex.com/ws/cnty/v8", partName = "ValidatePostalRequest")
        ValidatePostalRequest validatePostalRequest);

}
