
package com.fedex.ws.cnty.v8;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CountryService", targetNamespace = "http://fedex.com/ws/cnty/v8", wsdlLocation = "ws/fedex/wsdl/CountryService_v8.wsdl")
public class CountryService
    extends Service
{

    private final static URL COUNTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYSERVICE_EXCEPTION;
    private final static QName COUNTRYSERVICE_QNAME = new QName("http://fedex.com/ws/cnty/v8", "CountryService");

    static {
        COUNTRYSERVICE_WSDL_LOCATION = com.fedex.ws.cnty.v8.CountryService.class.getResource("ws/fedex/wsdl/CountryService_v8.wsdl");
        WebServiceException e = null;
        if (COUNTRYSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/CountryService_v8.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COUNTRYSERVICE_EXCEPTION = e;
    }

    public CountryService() {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME);
    }

    public CountryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME);
    }

    public CountryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryPortType
     */
    @WebEndpoint(name = "CountryServicePort")
    public CountryPortType getCountryServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/cnty/v8", "CountryServicePort"), CountryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryPortType
     */
    @WebEndpoint(name = "CountryServicePort")
    public CountryPortType getCountryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/cnty/v8", "CountryServicePort"), CountryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYSERVICE_EXCEPTION!= null) {
            throw COUNTRYSERVICE_EXCEPTION;
        }
        return COUNTRYSERVICE_WSDL_LOCATION;
    }

}
