
package com.ups.wsdl.xoltws.xav.v1;

import java.util.concurrent.Future;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import com.ups.xmlschema.xoltws.xav.v1.XAVRequest;
import com.ups.xmlschema.xoltws.xav.v1.XAVResponse;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "XAVPortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/XAV/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.xav.v1.ObjectFactory.class
})
public interface XAVPortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws.xav.v1.XAVResponse>
     */
    @WebMethod(operationName = "ProcessXAV", action = "http://onlinetools.ups.com/webservices/XAVBinding/v1.0")
    public Response<XAVResponse> processXAVAsync(
        @WebParam(name = "XAVRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", partName = "Body")
        XAVRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessXAV", action = "http://onlinetools.ups.com/webservices/XAVBinding/v1.0")
    public Future<?> processXAVAsync(
        @WebParam(name = "XAVRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", partName = "Body")
        XAVRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessXAVResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<XAVResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.xav.v1.XAVResponse
     * @throws XAVErrorMessage
     */
    @WebMethod(operationName = "ProcessXAV", action = "http://onlinetools.ups.com/webservices/XAVBinding/v1.0")
    @WebResult(name = "XAVResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", partName = "Body")
    public XAVResponse processXAV(
        @WebParam(name = "XAVRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", partName = "Body")
        XAVRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws XAVErrorMessage
    ;

}
