
package com.ups.wsdl.xoltws.xav.v1;

import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import com.ups.xmlschema.xoltws.xav.v1.XAVRequest;
import com.ups.xmlschema.xoltws.xav.v1.XAVResponse;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "XAVPort", serviceName = "XAVService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/XAV/v1.0", wsdlLocation = "ws/ups/wsdl/XAV.wsdl", endpointInterface = "com.ups.wsdl.xoltws.xav.v1.XAVPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class XAVService_XAVPortImpl
    implements XAVPortType
{


    public XAVService_XAVPortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.xav.v1.XAVResponse
     * @throws XAVErrorMessage
     */
    public XAVResponse processXAV(XAVRequest body, UPSSecurity upsSecurity)
        throws XAVErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
