
package com.ups.wsdl.xoltws._void.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "VoidService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Void/v1.1", wsdlLocation = "ws/ups/wsdl/Void.wsdl")
public class VoidService
    extends Service
{

    private final static URL VOIDSERVICE_WSDL_LOCATION;
    private final static WebServiceException VOIDSERVICE_EXCEPTION;
    private final static QName VOIDSERVICE_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/Void/v1.1", "VoidService");

    static {
        VOIDSERVICE_WSDL_LOCATION = com.ups.wsdl.xoltws._void.v1.VoidService.class.getResource("ws/ups/wsdl/Void.wsdl");
        WebServiceException e = null;
        if (VOIDSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/Void.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        VOIDSERVICE_EXCEPTION = e;
    }

    public VoidService() {
        super(__getWsdlLocation(), VOIDSERVICE_QNAME);
    }

    public VoidService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOIDSERVICE_QNAME, features);
    }

    public VoidService(URL wsdlLocation) {
        super(wsdlLocation, VOIDSERVICE_QNAME);
    }

    public VoidService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOIDSERVICE_QNAME, features);
    }

    public VoidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoidService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VoidPortType
     */
    @WebEndpoint(name = "VoidPort")
    public VoidPortType getVoidPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/Void/v1.1", "VoidPort"), VoidPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VoidPortType
     */
    @WebEndpoint(name = "VoidPort")
    public VoidPortType getVoidPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/Void/v1.1", "VoidPort"), VoidPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOIDSERVICE_EXCEPTION!= null) {
            throw VOIDSERVICE_EXCEPTION;
        }
        return VOIDSERVICE_WSDL_LOCATION;
    }

}
