
package com.ups.wsdl.xoltws._void.v1;

import com.ups.xmlschema.xoltws._void.v1.VoidShipmentRequest;
import com.ups.xmlschema.xoltws._void.v1.VoidShipmentResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "VoidPort", serviceName = "VoidService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Void/v1.1", wsdlLocation = "ws/ups/wsdl/Void.wsdl", endpointInterface = "com.ups.wsdl.xoltws._void.v1.VoidPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class VoidService_VoidPortImpl
    implements VoidPortType
{


    public VoidService_VoidPortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws._void.v1.VoidShipmentResponse
     * @throws VoidErrorMessage
     */
    public VoidShipmentResponse processVoid(VoidShipmentRequest body, UPSSecurity upsSecurity)
        throws VoidErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
