
package com.ups.wsdl.xoltws._void.v1;

import java.util.concurrent.Future;
import com.ups.xmlschema.xoltws._void.v1.VoidShipmentRequest;
import com.ups.xmlschema.xoltws._void.v1.VoidShipmentResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "VoidPortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Void/v1.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws._void.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class
})
public interface VoidPortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws._void.v1.VoidShipmentResponse>
     */
    @WebMethod(operationName = "ProcessVoid", action = "http://onlinetools.ups.com/webservices/VoidBinding/v1.1")
    public Response<VoidShipmentResponse> processVoidAsync(
        @WebParam(name = "VoidShipmentRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1", partName = "Body")
        VoidShipmentRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessVoid", action = "http://onlinetools.ups.com/webservices/VoidBinding/v1.1")
    public Future<?> processVoidAsync(
        @WebParam(name = "VoidShipmentRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1", partName = "Body")
        VoidShipmentRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessVoidResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<VoidShipmentResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws._void.v1.VoidShipmentResponse
     * @throws VoidErrorMessage
     */
    @WebMethod(operationName = "ProcessVoid", action = "http://onlinetools.ups.com/webservices/VoidBinding/v1.1")
    @WebResult(name = "VoidShipmentResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1", partName = "Body")
    public VoidShipmentResponse processVoid(
        @WebParam(name = "VoidShipmentRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1", partName = "Body")
        VoidShipmentRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws VoidErrorMessage
    ;

}
