
package com.fedex.ws.async.v4;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ASYNCService", targetNamespace = "http://fedex.com/ws/async/v4", wsdlLocation = "ws/fedex/wsdl/ASYNCService_v4.wsdl")
public class ASYNCService
    extends Service
{

    private final static URL ASYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASYNCSERVICE_EXCEPTION;
    private final static QName ASYNCSERVICE_QNAME = new QName("http://fedex.com/ws/async/v4", "ASYNCService");

    static {
        ASYNCSERVICE_WSDL_LOCATION = com.fedex.ws.async.v4.ASYNCService.class.getResource("ws/fedex/wsdl/ASYNCService_v4.wsdl");
        WebServiceException e = null;
        if (ASYNCSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/ASYNCService_v4.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ASYNCSERVICE_EXCEPTION = e;
    }

    public ASYNCService() {
        super(__getWsdlLocation(), ASYNCSERVICE_QNAME);
    }

    public ASYNCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASYNCSERVICE_QNAME, features);
    }

    public ASYNCService(URL wsdlLocation) {
        super(wsdlLocation, ASYNCSERVICE_QNAME);
    }

    public ASYNCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASYNCSERVICE_QNAME, features);
    }

    public ASYNCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ASYNCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ASYNCPortType
     */
    @WebEndpoint(name = "ASYNCServicePort")
    public ASYNCPortType getASYNCServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/async/v4", "ASYNCServicePort"), ASYNCPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ASYNCPortType
     */
    @WebEndpoint(name = "ASYNCServicePort")
    public ASYNCPortType getASYNCServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/async/v4", "ASYNCServicePort"), ASYNCPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASYNCSERVICE_EXCEPTION!= null) {
            throw ASYNCSERVICE_EXCEPTION;
        }
        return ASYNCSERVICE_WSDL_LOCATION;
    }

}
