
package com.fedex.ws.async.v4;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "ASYNCServicePort", serviceName = "ASYNCService", targetNamespace = "http://fedex.com/ws/async/v4", wsdlLocation = "ws/fedex/wsdl/ASYNCService_v4.wsdl", endpointInterface = "com.fedex.ws.async.v4.ASYNCPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ASYNCService_ASYNCServicePortImpl
    implements ASYNCPortType
{


    public ASYNCService_ASYNCServicePortImpl() {
    }

    /**
     * 
     * @param retrieveJobResultsRequest
     * @return
     *     returns com.fedex.ws.async.v4.RetrieveJobResultsReply
     */
    public RetrieveJobResultsReply retrieveJobResults(RetrieveJobResultsRequest retrieveJobResultsRequest) {
        //replace with your impl here
        return null;
    }

}
