
package com.fedex.ws.async.v4;

import java.util.concurrent.Future;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ASYNCPortType", targetNamespace = "http://fedex.com/ws/async/v4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ASYNCPortType {


    /**
     * 
     * @param retrieveJobResultsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.async.v4.RetrieveJobResultsReply>
     */
    @WebMethod(operationName = "retrieveJobResults", action = "http://fedex.com/ws/async/v4/retrieveJobResults")
    public Response<RetrieveJobResultsReply> retrieveJobResultsAsync(
        @WebParam(name = "RetrieveJobResultsRequest", targetNamespace = "http://fedex.com/ws/async/v4", partName = "RetrieveJobResultsRequest")
        RetrieveJobResultsRequest retrieveJobResultsRequest);

    /**
     * 
     * @param asyncHandler
     * @param retrieveJobResultsRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "retrieveJobResults", action = "http://fedex.com/ws/async/v4/retrieveJobResults")
    public Future<?> retrieveJobResultsAsync(
        @WebParam(name = "RetrieveJobResultsRequest", targetNamespace = "http://fedex.com/ws/async/v4", partName = "RetrieveJobResultsRequest")
        RetrieveJobResultsRequest retrieveJobResultsRequest,
        @WebParam(name = "retrieveJobResultsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RetrieveJobResultsReply> asyncHandler);

    /**
     * 
     * @param retrieveJobResultsRequest
     * @return
     *     returns com.fedex.ws.async.v4.RetrieveJobResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/async/v4/retrieveJobResults")
    @WebResult(name = "RetrieveJobResultsReply", targetNamespace = "http://fedex.com/ws/async/v4", partName = "RetrieveJobResultsReply")
    public RetrieveJobResultsReply retrieveJobResults(
        @WebParam(name = "RetrieveJobResultsRequest", targetNamespace = "http://fedex.com/ws/async/v4", partName = "RetrieveJobResultsRequest")
        RetrieveJobResultsRequest retrieveJobResultsRequest);

}
