
package com.ups.wsdl.xoltws.dangerousgoodsutility.v1;

import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckRequest;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckResponse;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataRequest;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "DangerousGoodsUtilityPort", serviceName = "DangerousGoodsUtility", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0", wsdlLocation = "ws/ups/wsdl/DangerousGoodsUtility.wsdl", endpointInterface = "com.ups.wsdl.xoltws.dangerousgoodsutility.v1.DangerousGoodsUtilityPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class DangerousGoodsUtility_DangerousGoodsUtilityPortImpl
    implements DangerousGoodsUtilityPortType
{


    public DangerousGoodsUtility_DangerousGoodsUtilityPortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckResponse
     * @throws AcceptanceAuditPreCheckErrorMessage
     */
    public AcceptanceAuditPreCheckResponse processAcceptanceAuditPreCheck(AcceptanceAuditPreCheckRequest body, UPSSecurity upsSecurity)
        throws AcceptanceAuditPreCheckErrorMessage
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataResponse
     * @throws ChemicalReferenceDataErrorMessage
     */
    public ChemicalReferenceDataResponse processChemicalReferenceData(ChemicalReferenceDataRequest body, UPSSecurity upsSecurity)
        throws ChemicalReferenceDataErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
