
package com.ups.wsdl.xoltws.dangerousgoodsutility.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DangerousGoodsUtility", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0", wsdlLocation = "ws/ups/wsdl/DangerousGoodsUtility.wsdl")
public class DangerousGoodsUtility
    extends Service
{

    private final static URL DANGEROUSGOODSUTILITY_WSDL_LOCATION;
    private final static WebServiceException DANGEROUSGOODSUTILITY_EXCEPTION;
    private final static QName DANGEROUSGOODSUTILITY_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0", "DangerousGoodsUtility");

    static {
        DANGEROUSGOODSUTILITY_WSDL_LOCATION = com.ups.wsdl.xoltws.dangerousgoodsutility.v1.DangerousGoodsUtility.class.getResource("ws/ups/wsdl/DangerousGoodsUtility.wsdl");
        WebServiceException e = null;
        if (DANGEROUSGOODSUTILITY_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/DangerousGoodsUtility.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DANGEROUSGOODSUTILITY_EXCEPTION = e;
    }

    public DangerousGoodsUtility() {
        super(__getWsdlLocation(), DANGEROUSGOODSUTILITY_QNAME);
    }

    public DangerousGoodsUtility(WebServiceFeature... features) {
        super(__getWsdlLocation(), DANGEROUSGOODSUTILITY_QNAME, features);
    }

    public DangerousGoodsUtility(URL wsdlLocation) {
        super(wsdlLocation, DANGEROUSGOODSUTILITY_QNAME);
    }

    public DangerousGoodsUtility(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DANGEROUSGOODSUTILITY_QNAME, features);
    }

    public DangerousGoodsUtility(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DangerousGoodsUtility(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DangerousGoodsUtilityPortType
     */
    @WebEndpoint(name = "DangerousGoodsUtilityPort")
    public DangerousGoodsUtilityPortType getDangerousGoodsUtilityPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0", "DangerousGoodsUtilityPort"), DangerousGoodsUtilityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DangerousGoodsUtilityPortType
     */
    @WebEndpoint(name = "DangerousGoodsUtilityPort")
    public DangerousGoodsUtilityPortType getDangerousGoodsUtilityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0", "DangerousGoodsUtilityPort"), DangerousGoodsUtilityPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DANGEROUSGOODSUTILITY_EXCEPTION!= null) {
            throw DANGEROUSGOODSUTILITY_EXCEPTION;
        }
        return DANGEROUSGOODSUTILITY_WSDL_LOCATION;
    }

}
