
package com.ups.wsdl.xoltws.dangerousgoodsutility.v1;

import java.util.concurrent.Future;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckRequest;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckResponse;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataRequest;
import com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DangerousGoodsUtilityPortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class
})
public interface DangerousGoodsUtilityPortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckResponse>
     */
    @WebMethod(operationName = "ProcessAcceptanceAuditPreCheck", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    public Response<AcceptanceAuditPreCheckResponse> processAcceptanceAuditPreCheckAsync(
        @WebParam(name = "AcceptanceAuditPreCheckRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        AcceptanceAuditPreCheckRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessAcceptanceAuditPreCheck", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    public Future<?> processAcceptanceAuditPreCheckAsync(
        @WebParam(name = "AcceptanceAuditPreCheckRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        AcceptanceAuditPreCheckRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessAcceptanceAuditPreCheckResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AcceptanceAuditPreCheckResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.AcceptanceAuditPreCheckResponse
     * @throws AcceptanceAuditPreCheckErrorMessage
     */
    @WebMethod(operationName = "ProcessAcceptanceAuditPreCheck", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    @WebResult(name = "AcceptanceAuditPreCheckResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
    public AcceptanceAuditPreCheckResponse processAcceptanceAuditPreCheck(
        @WebParam(name = "AcceptanceAuditPreCheckRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        AcceptanceAuditPreCheckRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws AcceptanceAuditPreCheckErrorMessage
    ;

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataResponse>
     */
    @WebMethod(operationName = "ProcessChemicalReferenceData", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    public Response<ChemicalReferenceDataResponse> processChemicalReferenceDataAsync(
        @WebParam(name = "ChemicalReferenceDataRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        ChemicalReferenceDataRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessChemicalReferenceData", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    public Future<?> processChemicalReferenceDataAsync(
        @WebParam(name = "ChemicalReferenceDataRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        ChemicalReferenceDataRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessChemicalReferenceDataResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ChemicalReferenceDataResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.dangerousgoodsutility.v1.ChemicalReferenceDataResponse
     * @throws ChemicalReferenceDataErrorMessage
     */
    @WebMethod(operationName = "ProcessChemicalReferenceData", action = "http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0")
    @WebResult(name = "ChemicalReferenceDataResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
    public ChemicalReferenceDataResponse processChemicalReferenceData(
        @WebParam(name = "ChemicalReferenceDataRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0", partName = "Body")
        ChemicalReferenceDataRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws ChemicalReferenceDataErrorMessage
    ;

}
