
package com.fedex.ws.track.v19;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TrackPortType", targetNamespace = "http://fedex.com/ws/track/v19")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackPortType {


    /**
     * 
     * @param trackRequest
     * @return
     *     returns com.fedex.ws.track.v19.TrackReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v19/track")
    @WebResult(name = "TrackReply", targetNamespace = "http://fedex.com/ws/track/v19", partName = "TrackReply")
    public TrackReply track(
        @WebParam(name = "TrackRequest", targetNamespace = "http://fedex.com/ws/track/v19", partName = "TrackRequest")
        TrackRequest trackRequest);

    /**
     * 
     * @param getTrackingDocumentsRequest
     * @return
     *     returns com.fedex.ws.track.v19.GetTrackingDocumentsReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v19/getTrackingDocuments")
    @WebResult(name = "GetTrackingDocumentsReply", targetNamespace = "http://fedex.com/ws/track/v19", partName = "GetTrackingDocumentsReply")
    public GetTrackingDocumentsReply getTrackingDocuments(
        @WebParam(name = "GetTrackingDocumentsRequest", targetNamespace = "http://fedex.com/ws/track/v19", partName = "GetTrackingDocumentsRequest")
        GetTrackingDocumentsRequest getTrackingDocumentsRequest);

    /**
     * 
     * @param sendNotificationsRequest
     * @return
     *     returns com.fedex.ws.track.v19.SendNotificationsReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v19/sendNotifications")
    @WebResult(name = "SendNotificationsReply", targetNamespace = "http://fedex.com/ws/track/v19", partName = "SendNotificationsReply")
    public SendNotificationsReply sendNotifications(
        @WebParam(name = "SendNotificationsRequest", targetNamespace = "http://fedex.com/ws/track/v19", partName = "SendNotificationsRequest")
        SendNotificationsRequest sendNotificationsRequest);

}
