
package com.fedex.ws.track.v19;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "TrackServicePort", serviceName = "TrackService", targetNamespace = "http://fedex.com/ws/track/v19", wsdlLocation = "ws/fedex/wsdl/TrackService_v19.wsdl", endpointInterface = "com.fedex.ws.track.v19.TrackPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class TrackService_TrackServicePortImpl
    implements TrackPortType
{


    public TrackService_TrackServicePortImpl() {
    }

    /**
     * 
     * @param trackRequest
     * @return
     *     returns com.fedex.ws.track.v19.TrackReply
     */
    public TrackReply track(TrackRequest trackRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getTrackingDocumentsRequest
     * @return
     *     returns com.fedex.ws.track.v19.GetTrackingDocumentsReply
     */
    public GetTrackingDocumentsReply getTrackingDocuments(GetTrackingDocumentsRequest getTrackingDocumentsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param sendNotificationsRequest
     * @return
     *     returns com.fedex.ws.track.v19.SendNotificationsReply
     */
    public SendNotificationsReply sendNotifications(SendNotificationsRequest sendNotificationsRequest) {
        //replace with your impl here
        return null;
    }

}
