
package com.fedex.ws.ifss.v1;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "IFSSServicePort", serviceName = "IFSSService", targetNamespace = "http://fedex.com/ws/ifss/v1", wsdlLocation = "ws/fedex/wsdl/InFlightShipmentService_v1.wsdl", endpointInterface = "com.fedex.ws.ifss.v1.IFSSPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class IFSSService_IFSSServicePortImpl
    implements IFSSPortType
{


    public IFSSService_IFSSServicePortImpl() {
    }

    /**
     * 
     * @param validateDeliveryRequest
     * @return
     *     returns com.fedex.ws.ifss.v1.ValidateDeliveryReply
     */
    public ValidateDeliveryReply validateDelivery(ValidateDeliveryRequest validateDeliveryRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param processDeliveryRequest
     * @return
     *     returns com.fedex.ws.ifss.v1.ProcessDeliveryReply
     */
    public ProcessDeliveryReply processDelivery(ProcessDeliveryRequest processDeliveryRequest) {
        //replace with your impl here
        return null;
    }

}
