
package com.fedex.ws.ifss.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "IFSSService", targetNamespace = "http://fedex.com/ws/ifss/v1", wsdlLocation = "ws/fedex/wsdl/InFlightShipmentService_v1.wsdl")
public class IFSSService
    extends Service
{

    private final static URL IFSSSERVICE_WSDL_LOCATION;
    private final static WebServiceException IFSSSERVICE_EXCEPTION;
    private final static QName IFSSSERVICE_QNAME = new QName("http://fedex.com/ws/ifss/v1", "IFSSService");

    static {
        IFSSSERVICE_WSDL_LOCATION = com.fedex.ws.ifss.v1.IFSSService.class.getResource("ws/fedex/wsdl/InFlightShipmentService_v1.wsdl");
        WebServiceException e = null;
        if (IFSSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/InFlightShipmentService_v1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        IFSSSERVICE_EXCEPTION = e;
    }

    public IFSSService() {
        super(__getWsdlLocation(), IFSSSERVICE_QNAME);
    }

    public IFSSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IFSSSERVICE_QNAME, features);
    }

    public IFSSService(URL wsdlLocation) {
        super(wsdlLocation, IFSSSERVICE_QNAME);
    }

    public IFSSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IFSSSERVICE_QNAME, features);
    }

    public IFSSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFSSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFSSPortType
     */
    @WebEndpoint(name = "IFSSServicePort")
    public IFSSPortType getIFSSServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/ifss/v1", "IFSSServicePort"), IFSSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFSSPortType
     */
    @WebEndpoint(name = "IFSSServicePort")
    public IFSSPortType getIFSSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/ifss/v1", "IFSSServicePort"), IFSSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IFSSSERVICE_EXCEPTION!= null) {
            throw IFSSSERVICE_EXCEPTION;
        }
        return IFSSSERVICE_WSDL_LOCATION;
    }

}
