
package com.ups.wsdl.xoltws.tnt.v1;

import com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitRequest;
import com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "TimeInTransitPort", serviceName = "TimeInTransitService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", wsdlLocation = "ws/ups/wsdl/TNTWS.wsdl", endpointInterface = "com.ups.wsdl.xoltws.tnt.v1.TimeInTransitPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class TimeInTransitService_TimeInTransitPortImpl
    implements TimeInTransitPortType
{


    public TimeInTransitService_TimeInTransitPortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitResponse
     * @throws TimeInTransitErrorMessage
     */
    public TimeInTransitResponse processTimeInTransit(TimeInTransitRequest body, UPSSecurity upsSecurity)
        throws TimeInTransitErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
