
package com.ups.wsdl.xoltws.tnt.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TimeInTransitService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", wsdlLocation = "ws/ups/wsdl/TNTWS.wsdl")
public class TimeInTransitService
    extends Service
{

    private final static URL TIMEINTRANSITSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMEINTRANSITSERVICE_EXCEPTION;
    private final static QName TIMEINTRANSITSERVICE_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", "TimeInTransitService");

    static {
        TIMEINTRANSITSERVICE_WSDL_LOCATION = com.ups.wsdl.xoltws.tnt.v1.TimeInTransitService.class.getResource("ws/ups/wsdl/TNTWS.wsdl");
        WebServiceException e = null;
        if (TIMEINTRANSITSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/ups/wsdl/TNTWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TIMEINTRANSITSERVICE_EXCEPTION = e;
    }

    public TimeInTransitService() {
        super(__getWsdlLocation(), TIMEINTRANSITSERVICE_QNAME);
    }

    public TimeInTransitService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMEINTRANSITSERVICE_QNAME, features);
    }

    public TimeInTransitService(URL wsdlLocation) {
        super(wsdlLocation, TIMEINTRANSITSERVICE_QNAME);
    }

    public TimeInTransitService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMEINTRANSITSERVICE_QNAME, features);
    }

    public TimeInTransitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeInTransitService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeInTransitPortType
     */
    @WebEndpoint(name = "TimeInTransitPort")
    public TimeInTransitPortType getTimeInTransitPort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", "TimeInTransitPort"), TimeInTransitPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeInTransitPortType
     */
    @WebEndpoint(name = "TimeInTransitPort")
    public TimeInTransitPortType getTimeInTransitPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", "TimeInTransitPort"), TimeInTransitPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMEINTRANSITSERVICE_EXCEPTION!= null) {
            throw TIMEINTRANSITSERVICE_EXCEPTION;
        }
        return TIMEINTRANSITSERVICE_WSDL_LOCATION;
    }

}
