
package com.ups.wsdl.xoltws.tnt.v1;

import java.util.concurrent.Future;
import com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitRequest;
import com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TimeInTransitPortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/TNT/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.tnt.v1.ObjectFactory.class
})
public interface TimeInTransitPortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitResponse>
     */
    @WebMethod(operationName = "ProcessTimeInTransit", action = "http://onlinetools.ups.com/webservices/TimeInTransitBinding/v1.0")
    public Response<TimeInTransitResponse> processTimeInTransitAsync(
        @WebParam(name = "TimeInTransitRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0", partName = "Body")
        TimeInTransitRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessTimeInTransit", action = "http://onlinetools.ups.com/webservices/TimeInTransitBinding/v1.0")
    public Future<?> processTimeInTransitAsync(
        @WebParam(name = "TimeInTransitRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0", partName = "Body")
        TimeInTransitRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessTimeInTransitResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<TimeInTransitResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.tnt.v1.TimeInTransitResponse
     * @throws TimeInTransitErrorMessage
     */
    @WebMethod(operationName = "ProcessTimeInTransit", action = "http://onlinetools.ups.com/webservices/TimeInTransitBinding/v1.0")
    @WebResult(name = "TimeInTransitResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0", partName = "Body")
    public TimeInTransitResponse processTimeInTransit(
        @WebParam(name = "TimeInTransitRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0", partName = "Body")
        TimeInTransitRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws TimeInTransitErrorMessage
    ;

}
