
package com.fedex.ws.openship.v18;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "OpenShipPortType", targetNamespace = "http://fedex.com/ws/openship/v18")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenShipPortType {


    /**
     * 
     * @param modifyConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyConsolidation")
    @WebResult(name = "ModifyConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationReply")
    public ModifyConsolidationReply modifyConsolidation(
        @WebParam(name = "ModifyConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationRequest")
        ModifyConsolidationRequest modifyConsolidationRequest);

    /**
     * 
     * @param validateOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ValidateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/validateOpenShipment")
    @WebResult(name = "ValidateOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentReply")
    public ValidateOpenShipmentReply validateOpenShipment(
        @WebParam(name = "ValidateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentRequest")
        ValidateOpenShipmentRequest validateOpenShipmentRequest);

    /**
     * 
     * @param retrieveOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveOpenShipment")
    @WebResult(name = "RetrieveOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentReply")
    public RetrieveOpenShipmentReply retrieveOpenShipment(
        @WebParam(name = "RetrieveOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentRequest")
        RetrieveOpenShipmentRequest retrieveOpenShipmentRequest);

    /**
     * 
     * @param deleteOpenConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteOpenConsolidation")
    @WebResult(name = "DeleteOpenConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationReply")
    public DeleteOpenConsolidationReply deleteOpenConsolidation(
        @WebParam(name = "DeleteOpenConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationRequest")
        DeleteOpenConsolidationRequest deleteOpenConsolidationRequest);

    /**
     * 
     * @param createConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createConsolidation")
    @WebResult(name = "CreateConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationReply")
    public CreateConsolidationReply createConsolidation(
        @WebParam(name = "CreateConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationRequest")
        CreateConsolidationRequest createConsolidationRequest);

    /**
     * 
     * @param retrievePackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrievePackageInOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrievePackageInOpenShipment")
    @WebResult(name = "RetrievePackageInOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentReply")
    public RetrievePackageInOpenShipmentReply retrievePackageInOpenShipment(
        @WebParam(name = "RetrievePackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentRequest")
        RetrievePackageInOpenShipmentRequest retrievePackageInOpenShipmentRequest);

    /**
     * 
     * @param retrieveConsolidatedCommoditiesRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidatedCommoditiesReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveConsolidatedCommodities")
    @WebResult(name = "RetrieveConsolidatedCommoditiesReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesReply")
    public RetrieveConsolidatedCommoditiesReply retrieveConsolidatedCommodities(
        @WebParam(name = "RetrieveConsolidatedCommoditiesRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesRequest")
        RetrieveConsolidatedCommoditiesRequest retrieveConsolidatedCommoditiesRequest);

    /**
     * 
     * @param modifyPackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyPackageInOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyPackageInOpenShipment")
    @WebResult(name = "ModifyPackageInOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentReply")
    public ModifyPackageInOpenShipmentReply modifyPackageInOpenShipment(
        @WebParam(name = "ModifyPackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentRequest")
        ModifyPackageInOpenShipmentRequest modifyPackageInOpenShipmentRequest);

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ShipmentReply")
    public ShipmentReply deleteShipment(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest);

    /**
     * 
     * @param createOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createOpenShipment")
    @WebResult(name = "CreateOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentReply")
    public CreateOpenShipmentReply createOpenShipment(
        @WebParam(name = "CreateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentRequest")
        CreateOpenShipmentRequest createOpenShipmentRequest);

    /**
     * 
     * @param deletePendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePendingShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deletePendingShipment")
    @WebResult(name = "DeletePendingShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentReply")
    public DeletePendingShipmentReply deletePendingShipment(
        @WebParam(name = "DeletePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentRequest")
        DeletePendingShipmentRequest deletePendingShipmentRequest);

    /**
     * 
     * @param confirmOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/confirmOpenShipment")
    @WebResult(name = "ConfirmOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentReply")
    public ConfirmOpenShipmentReply confirmOpenShipment(
        @WebParam(name = "ConfirmOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentRequest")
        ConfirmOpenShipmentRequest confirmOpenShipmentRequest);

    /**
     * 
     * @param getConfirmOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getConfirmOpenShipmentResults")
    @WebResult(name = "GetConfirmOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsReply")
    public GetConfirmOpenShipmentResultsReply getConfirmOpenShipmentResults(
        @WebParam(name = "GetConfirmOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsRequest")
        GetConfirmOpenShipmentResultsRequest getConfirmOpenShipmentResultsRequest);

    /**
     * 
     * @param getConfirmConsolidationResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmConsolidationResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getConfirmConsolidationResults")
    @WebResult(name = "GetConfirmConsolidationResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsReply")
    public GetConfirmConsolidationResultsReply getConfirmConsolidationResults(
        @WebParam(name = "GetConfirmConsolidationResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsRequest")
        GetConfirmConsolidationResultsRequest getConfirmConsolidationResultsRequest);

    /**
     * 
     * @param modifyOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyOpenShipment")
    @WebResult(name = "ModifyOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentReply")
    public ModifyOpenShipmentReply modifyOpenShipment(
        @WebParam(name = "ModifyOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentRequest")
        ModifyOpenShipmentRequest modifyOpenShipmentRequest);

    /**
     * 
     * @param confirmConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/confirmConsolidation")
    @WebResult(name = "ConfirmConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationReply")
    public ConfirmConsolidationReply confirmConsolidation(
        @WebParam(name = "ConfirmConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationRequest")
        ConfirmConsolidationRequest confirmConsolidationRequest);

    /**
     * 
     * @param createPendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createPendingShipment")
    @WebResult(name = "CreatePendingShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentReply")
    public CreateOpenShipmentReply createPendingShipment(
        @WebParam(name = "CreatePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentRequest")
        CreateOpenShipmentRequest createPendingShipmentRequest);

    /**
     * 
     * @param getModifyOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetModifyOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getModifyOpenShipmentResults")
    @WebResult(name = "GetModifyOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsReply")
    public GetModifyOpenShipmentResultsReply getModifyOpenShipmentResults(
        @WebParam(name = "GetModifyOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsRequest")
        GetModifyOpenShipmentResultsRequest getModifyOpenShipmentResultsRequest);

    /**
     * 
     * @param deletePackagesFromOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePackagesFromOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deletePackagesFromOpenShipment")
    @WebResult(name = "DeletePackagesFromOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentReply")
    public DeletePackagesFromOpenShipmentReply deletePackagesFromOpenShipment(
        @WebParam(name = "DeletePackagesFromOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentRequest")
        DeletePackagesFromOpenShipmentRequest deletePackagesFromOpenShipmentRequest);

    /**
     * 
     * @param reprintShippingDocumentsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ReprintShippingDocumentsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/reprintShippingDocuments")
    @WebResult(name = "ReprintShippingDocumentsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsReply")
    public ReprintShippingDocumentsReply reprintShippingDocuments(
        @WebParam(name = "ReprintShippingDocumentsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsRequest")
        ReprintShippingDocumentsRequest reprintShippingDocumentsRequest);

    /**
     * 
     * @param addPackagesToOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.AddPackagesToOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/addPackagesToOpenShipment")
    @WebResult(name = "AddPackagesToOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentReply")
    public AddPackagesToOpenShipmentReply addPackagesToOpenShipment(
        @WebParam(name = "AddPackagesToOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentRequest")
        AddPackagesToOpenShipmentRequest addPackagesToOpenShipmentRequest);

    /**
     * 
     * @param getCreateOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetCreateOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getCreateOpenShipmentResults")
    @WebResult(name = "GetCreateOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsReply")
    public GetCreateOpenShipmentResultsReply getCreateOpenShipmentResults(
        @WebParam(name = "GetCreateOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsRequest")
        GetCreateOpenShipmentResultsRequest getCreateOpenShipmentResultsRequest);

    /**
     * 
     * @param retrieveConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveConsolidation")
    @WebResult(name = "RetrieveConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationReply")
    public RetrieveConsolidationReply retrieveConsolidation(
        @WebParam(name = "RetrieveConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationRequest")
        RetrieveConsolidationRequest retrieveConsolidationRequest);

    /**
     * 
     * @param deleteOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteOpenShipment")
    @WebResult(name = "DeleteOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentReply")
    public DeleteOpenShipmentReply deleteOpenShipment(
        @WebParam(name = "DeleteOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentRequest")
        DeleteOpenShipmentRequest deleteOpenShipmentRequest);

}
