
package com.fedex.ws.openship.v18;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "OpenShipService", targetNamespace = "http://fedex.com/ws/openship/v18", wsdlLocation = "ws/fedex/wsdl/OpenshipService_v18.wsdl")
public class OpenShipService
    extends Service
{

    private final static URL OPENSHIPSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPENSHIPSERVICE_EXCEPTION;
    private final static QName OPENSHIPSERVICE_QNAME = new QName("http://fedex.com/ws/openship/v18", "OpenShipService");

    static {
        OPENSHIPSERVICE_WSDL_LOCATION = com.fedex.ws.openship.v18.OpenShipService.class.getResource("ws/fedex/wsdl/OpenshipService_v18.wsdl");
        WebServiceException e = null;
        if (OPENSHIPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'ws/fedex/wsdl/OpenshipService_v18.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        OPENSHIPSERVICE_EXCEPTION = e;
    }

    public OpenShipService() {
        super(__getWsdlLocation(), OPENSHIPSERVICE_QNAME);
    }

    public OpenShipService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENSHIPSERVICE_QNAME, features);
    }

    public OpenShipService(URL wsdlLocation) {
        super(wsdlLocation, OPENSHIPSERVICE_QNAME);
    }

    public OpenShipService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENSHIPSERVICE_QNAME, features);
    }

    public OpenShipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenShipService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenShipPortType
     */
    @WebEndpoint(name = "OpenShipServicePort")
    public OpenShipPortType getOpenShipServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/openship/v18", "OpenShipServicePort"), OpenShipPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenShipPortType
     */
    @WebEndpoint(name = "OpenShipServicePort")
    public OpenShipPortType getOpenShipServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/openship/v18", "OpenShipServicePort"), OpenShipPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENSHIPSERVICE_EXCEPTION!= null) {
            throw OPENSHIPSERVICE_EXCEPTION;
        }
        return OPENSHIPSERVICE_WSDL_LOCATION;
    }

}
