
package com.fedex.ws.openship.v18;

import java.util.concurrent.Future;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "OpenShipPortType", targetNamespace = "http://fedex.com/ws/openship/v18")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenShipPortType {


    /**
     * 
     * @param modifyConsolidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ModifyConsolidationReply>
     */
    @WebMethod(operationName = "modifyConsolidation", action = "http://fedex.com/ws/openship/v18/modifyConsolidation")
    public Response<ModifyConsolidationReply> modifyConsolidationAsync(
        @WebParam(name = "ModifyConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationRequest")
        ModifyConsolidationRequest modifyConsolidationRequest);

    /**
     * 
     * @param modifyConsolidationRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "modifyConsolidation", action = "http://fedex.com/ws/openship/v18/modifyConsolidation")
    public Future<?> modifyConsolidationAsync(
        @WebParam(name = "ModifyConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationRequest")
        ModifyConsolidationRequest modifyConsolidationRequest,
        @WebParam(name = "modifyConsolidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ModifyConsolidationReply> asyncHandler);

    /**
     * 
     * @param modifyConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyConsolidation")
    @WebResult(name = "ModifyConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationReply")
    public ModifyConsolidationReply modifyConsolidation(
        @WebParam(name = "ModifyConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyConsolidationRequest")
        ModifyConsolidationRequest modifyConsolidationRequest);

    /**
     * 
     * @param validateOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ValidateOpenShipmentReply>
     */
    @WebMethod(operationName = "validateOpenShipment", action = "http://fedex.com/ws/openship/v18/validateOpenShipment")
    public Response<ValidateOpenShipmentReply> validateOpenShipmentAsync(
        @WebParam(name = "ValidateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentRequest")
        ValidateOpenShipmentRequest validateOpenShipmentRequest);

    /**
     * 
     * @param validateOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "validateOpenShipment", action = "http://fedex.com/ws/openship/v18/validateOpenShipment")
    public Future<?> validateOpenShipmentAsync(
        @WebParam(name = "ValidateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentRequest")
        ValidateOpenShipmentRequest validateOpenShipmentRequest,
        @WebParam(name = "validateOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ValidateOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param validateOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ValidateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/validateOpenShipment")
    @WebResult(name = "ValidateOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentReply")
    public ValidateOpenShipmentReply validateOpenShipment(
        @WebParam(name = "ValidateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ValidateOpenShipmentRequest")
        ValidateOpenShipmentRequest validateOpenShipmentRequest);

    /**
     * 
     * @param retrieveOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.RetrieveOpenShipmentReply>
     */
    @WebMethod(operationName = "retrieveOpenShipment", action = "http://fedex.com/ws/openship/v18/retrieveOpenShipment")
    public Response<RetrieveOpenShipmentReply> retrieveOpenShipmentAsync(
        @WebParam(name = "RetrieveOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentRequest")
        RetrieveOpenShipmentRequest retrieveOpenShipmentRequest);

    /**
     * 
     * @param retrieveOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "retrieveOpenShipment", action = "http://fedex.com/ws/openship/v18/retrieveOpenShipment")
    public Future<?> retrieveOpenShipmentAsync(
        @WebParam(name = "RetrieveOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentRequest")
        RetrieveOpenShipmentRequest retrieveOpenShipmentRequest,
        @WebParam(name = "retrieveOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RetrieveOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param retrieveOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveOpenShipment")
    @WebResult(name = "RetrieveOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentReply")
    public RetrieveOpenShipmentReply retrieveOpenShipment(
        @WebParam(name = "RetrieveOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveOpenShipmentRequest")
        RetrieveOpenShipmentRequest retrieveOpenShipmentRequest);

    /**
     * 
     * @param deleteOpenConsolidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.DeleteOpenConsolidationReply>
     */
    @WebMethod(operationName = "deleteOpenConsolidation", action = "http://fedex.com/ws/openship/v18/deleteOpenConsolidation")
    public Response<DeleteOpenConsolidationReply> deleteOpenConsolidationAsync(
        @WebParam(name = "DeleteOpenConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationRequest")
        DeleteOpenConsolidationRequest deleteOpenConsolidationRequest);

    /**
     * 
     * @param deleteOpenConsolidationRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteOpenConsolidation", action = "http://fedex.com/ws/openship/v18/deleteOpenConsolidation")
    public Future<?> deleteOpenConsolidationAsync(
        @WebParam(name = "DeleteOpenConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationRequest")
        DeleteOpenConsolidationRequest deleteOpenConsolidationRequest,
        @WebParam(name = "deleteOpenConsolidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteOpenConsolidationReply> asyncHandler);

    /**
     * 
     * @param deleteOpenConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteOpenConsolidation")
    @WebResult(name = "DeleteOpenConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationReply")
    public DeleteOpenConsolidationReply deleteOpenConsolidation(
        @WebParam(name = "DeleteOpenConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenConsolidationRequest")
        DeleteOpenConsolidationRequest deleteOpenConsolidationRequest);

    /**
     * 
     * @param createConsolidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.CreateConsolidationReply>
     */
    @WebMethod(operationName = "createConsolidation", action = "http://fedex.com/ws/openship/v18/createConsolidation")
    public Response<CreateConsolidationReply> createConsolidationAsync(
        @WebParam(name = "CreateConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationRequest")
        CreateConsolidationRequest createConsolidationRequest);

    /**
     * 
     * @param createConsolidationRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createConsolidation", action = "http://fedex.com/ws/openship/v18/createConsolidation")
    public Future<?> createConsolidationAsync(
        @WebParam(name = "CreateConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationRequest")
        CreateConsolidationRequest createConsolidationRequest,
        @WebParam(name = "createConsolidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CreateConsolidationReply> asyncHandler);

    /**
     * 
     * @param createConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createConsolidation")
    @WebResult(name = "CreateConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationReply")
    public CreateConsolidationReply createConsolidation(
        @WebParam(name = "CreateConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateConsolidationRequest")
        CreateConsolidationRequest createConsolidationRequest);

    /**
     * 
     * @param retrievePackageInOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.RetrievePackageInOpenShipmentReply>
     */
    @WebMethod(operationName = "retrievePackageInOpenShipment", action = "http://fedex.com/ws/openship/v18/retrievePackageInOpenShipment")
    public Response<RetrievePackageInOpenShipmentReply> retrievePackageInOpenShipmentAsync(
        @WebParam(name = "RetrievePackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentRequest")
        RetrievePackageInOpenShipmentRequest retrievePackageInOpenShipmentRequest);

    /**
     * 
     * @param retrievePackageInOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "retrievePackageInOpenShipment", action = "http://fedex.com/ws/openship/v18/retrievePackageInOpenShipment")
    public Future<?> retrievePackageInOpenShipmentAsync(
        @WebParam(name = "RetrievePackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentRequest")
        RetrievePackageInOpenShipmentRequest retrievePackageInOpenShipmentRequest,
        @WebParam(name = "retrievePackageInOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RetrievePackageInOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param retrievePackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrievePackageInOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrievePackageInOpenShipment")
    @WebResult(name = "RetrievePackageInOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentReply")
    public RetrievePackageInOpenShipmentReply retrievePackageInOpenShipment(
        @WebParam(name = "RetrievePackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrievePackageInOpenShipmentRequest")
        RetrievePackageInOpenShipmentRequest retrievePackageInOpenShipmentRequest);

    /**
     * 
     * @param retrieveConsolidatedCommoditiesRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.RetrieveConsolidatedCommoditiesReply>
     */
    @WebMethod(operationName = "retrieveConsolidatedCommodities", action = "http://fedex.com/ws/openship/v18/retrieveConsolidatedCommodities")
    public Response<RetrieveConsolidatedCommoditiesReply> retrieveConsolidatedCommoditiesAsync(
        @WebParam(name = "RetrieveConsolidatedCommoditiesRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesRequest")
        RetrieveConsolidatedCommoditiesRequest retrieveConsolidatedCommoditiesRequest);

    /**
     * 
     * @param retrieveConsolidatedCommoditiesRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "retrieveConsolidatedCommodities", action = "http://fedex.com/ws/openship/v18/retrieveConsolidatedCommodities")
    public Future<?> retrieveConsolidatedCommoditiesAsync(
        @WebParam(name = "RetrieveConsolidatedCommoditiesRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesRequest")
        RetrieveConsolidatedCommoditiesRequest retrieveConsolidatedCommoditiesRequest,
        @WebParam(name = "retrieveConsolidatedCommoditiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RetrieveConsolidatedCommoditiesReply> asyncHandler);

    /**
     * 
     * @param retrieveConsolidatedCommoditiesRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidatedCommoditiesReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveConsolidatedCommodities")
    @WebResult(name = "RetrieveConsolidatedCommoditiesReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesReply")
    public RetrieveConsolidatedCommoditiesReply retrieveConsolidatedCommodities(
        @WebParam(name = "RetrieveConsolidatedCommoditiesRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidatedCommoditiesRequest")
        RetrieveConsolidatedCommoditiesRequest retrieveConsolidatedCommoditiesRequest);

    /**
     * 
     * @param modifyPackageInOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ModifyPackageInOpenShipmentReply>
     */
    @WebMethod(operationName = "modifyPackageInOpenShipment", action = "http://fedex.com/ws/openship/v18/modifyPackageInOpenShipment")
    public Response<ModifyPackageInOpenShipmentReply> modifyPackageInOpenShipmentAsync(
        @WebParam(name = "ModifyPackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentRequest")
        ModifyPackageInOpenShipmentRequest modifyPackageInOpenShipmentRequest);

    /**
     * 
     * @param modifyPackageInOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "modifyPackageInOpenShipment", action = "http://fedex.com/ws/openship/v18/modifyPackageInOpenShipment")
    public Future<?> modifyPackageInOpenShipmentAsync(
        @WebParam(name = "ModifyPackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentRequest")
        ModifyPackageInOpenShipmentRequest modifyPackageInOpenShipmentRequest,
        @WebParam(name = "modifyPackageInOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ModifyPackageInOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param modifyPackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyPackageInOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyPackageInOpenShipment")
    @WebResult(name = "ModifyPackageInOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentReply")
    public ModifyPackageInOpenShipmentReply modifyPackageInOpenShipment(
        @WebParam(name = "ModifyPackageInOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyPackageInOpenShipmentRequest")
        ModifyPackageInOpenShipmentRequest modifyPackageInOpenShipmentRequest);

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ShipmentReply>
     */
    @WebMethod(operationName = "deleteShipment", action = "http://fedex.com/ws/openship/v18/deleteShipment")
    public Response<ShipmentReply> deleteShipmentAsync(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest);

    /**
     * 
     * @param deleteShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteShipment", action = "http://fedex.com/ws/openship/v18/deleteShipment")
    public Future<?> deleteShipmentAsync(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest,
        @WebParam(name = "deleteShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ShipmentReply> asyncHandler);

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ShipmentReply")
    public ShipmentReply deleteShipment(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest);

    /**
     * 
     * @param createOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.CreateOpenShipmentReply>
     */
    @WebMethod(operationName = "createOpenShipment", action = "http://fedex.com/ws/openship/v18/createOpenShipment")
    public Response<CreateOpenShipmentReply> createOpenShipmentAsync(
        @WebParam(name = "CreateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentRequest")
        CreateOpenShipmentRequest createOpenShipmentRequest);

    /**
     * 
     * @param createOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createOpenShipment", action = "http://fedex.com/ws/openship/v18/createOpenShipment")
    public Future<?> createOpenShipmentAsync(
        @WebParam(name = "CreateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentRequest")
        CreateOpenShipmentRequest createOpenShipmentRequest,
        @WebParam(name = "createOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CreateOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param createOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createOpenShipment")
    @WebResult(name = "CreateOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentReply")
    public CreateOpenShipmentReply createOpenShipment(
        @WebParam(name = "CreateOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreateOpenShipmentRequest")
        CreateOpenShipmentRequest createOpenShipmentRequest);

    /**
     * 
     * @param deletePendingShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.DeletePendingShipmentReply>
     */
    @WebMethod(operationName = "deletePendingShipment", action = "http://fedex.com/ws/openship/v18/deletePendingShipment")
    public Response<DeletePendingShipmentReply> deletePendingShipmentAsync(
        @WebParam(name = "DeletePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentRequest")
        DeletePendingShipmentRequest deletePendingShipmentRequest);

    /**
     * 
     * @param deletePendingShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deletePendingShipment", action = "http://fedex.com/ws/openship/v18/deletePendingShipment")
    public Future<?> deletePendingShipmentAsync(
        @WebParam(name = "DeletePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentRequest")
        DeletePendingShipmentRequest deletePendingShipmentRequest,
        @WebParam(name = "deletePendingShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeletePendingShipmentReply> asyncHandler);

    /**
     * 
     * @param deletePendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePendingShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deletePendingShipment")
    @WebResult(name = "DeletePendingShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentReply")
    public DeletePendingShipmentReply deletePendingShipment(
        @WebParam(name = "DeletePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePendingShipmentRequest")
        DeletePendingShipmentRequest deletePendingShipmentRequest);

    /**
     * 
     * @param confirmOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ConfirmOpenShipmentReply>
     */
    @WebMethod(operationName = "confirmOpenShipment", action = "http://fedex.com/ws/openship/v18/confirmOpenShipment")
    public Response<ConfirmOpenShipmentReply> confirmOpenShipmentAsync(
        @WebParam(name = "ConfirmOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentRequest")
        ConfirmOpenShipmentRequest confirmOpenShipmentRequest);

    /**
     * 
     * @param confirmOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "confirmOpenShipment", action = "http://fedex.com/ws/openship/v18/confirmOpenShipment")
    public Future<?> confirmOpenShipmentAsync(
        @WebParam(name = "ConfirmOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentRequest")
        ConfirmOpenShipmentRequest confirmOpenShipmentRequest,
        @WebParam(name = "confirmOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ConfirmOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param confirmOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/confirmOpenShipment")
    @WebResult(name = "ConfirmOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentReply")
    public ConfirmOpenShipmentReply confirmOpenShipment(
        @WebParam(name = "ConfirmOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmOpenShipmentRequest")
        ConfirmOpenShipmentRequest confirmOpenShipmentRequest);

    /**
     * 
     * @param getConfirmOpenShipmentResultsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.GetConfirmOpenShipmentResultsReply>
     */
    @WebMethod(operationName = "getConfirmOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getConfirmOpenShipmentResults")
    public Response<GetConfirmOpenShipmentResultsReply> getConfirmOpenShipmentResultsAsync(
        @WebParam(name = "GetConfirmOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsRequest")
        GetConfirmOpenShipmentResultsRequest getConfirmOpenShipmentResultsRequest);

    /**
     * 
     * @param getConfirmOpenShipmentResultsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getConfirmOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getConfirmOpenShipmentResults")
    public Future<?> getConfirmOpenShipmentResultsAsync(
        @WebParam(name = "GetConfirmOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsRequest")
        GetConfirmOpenShipmentResultsRequest getConfirmOpenShipmentResultsRequest,
        @WebParam(name = "getConfirmOpenShipmentResultsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetConfirmOpenShipmentResultsReply> asyncHandler);

    /**
     * 
     * @param getConfirmOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getConfirmOpenShipmentResults")
    @WebResult(name = "GetConfirmOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsReply")
    public GetConfirmOpenShipmentResultsReply getConfirmOpenShipmentResults(
        @WebParam(name = "GetConfirmOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmOpenShipmentResultsRequest")
        GetConfirmOpenShipmentResultsRequest getConfirmOpenShipmentResultsRequest);

    /**
     * 
     * @param getConfirmConsolidationResultsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.GetConfirmConsolidationResultsReply>
     */
    @WebMethod(operationName = "getConfirmConsolidationResults", action = "http://fedex.com/ws/openship/v18/getConfirmConsolidationResults")
    public Response<GetConfirmConsolidationResultsReply> getConfirmConsolidationResultsAsync(
        @WebParam(name = "GetConfirmConsolidationResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsRequest")
        GetConfirmConsolidationResultsRequest getConfirmConsolidationResultsRequest);

    /**
     * 
     * @param getConfirmConsolidationResultsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getConfirmConsolidationResults", action = "http://fedex.com/ws/openship/v18/getConfirmConsolidationResults")
    public Future<?> getConfirmConsolidationResultsAsync(
        @WebParam(name = "GetConfirmConsolidationResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsRequest")
        GetConfirmConsolidationResultsRequest getConfirmConsolidationResultsRequest,
        @WebParam(name = "getConfirmConsolidationResultsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetConfirmConsolidationResultsReply> asyncHandler);

    /**
     * 
     * @param getConfirmConsolidationResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmConsolidationResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getConfirmConsolidationResults")
    @WebResult(name = "GetConfirmConsolidationResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsReply")
    public GetConfirmConsolidationResultsReply getConfirmConsolidationResults(
        @WebParam(name = "GetConfirmConsolidationResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetConfirmConsolidationResultsRequest")
        GetConfirmConsolidationResultsRequest getConfirmConsolidationResultsRequest);

    /**
     * 
     * @param modifyOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ModifyOpenShipmentReply>
     */
    @WebMethod(operationName = "modifyOpenShipment", action = "http://fedex.com/ws/openship/v18/modifyOpenShipment")
    public Response<ModifyOpenShipmentReply> modifyOpenShipmentAsync(
        @WebParam(name = "ModifyOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentRequest")
        ModifyOpenShipmentRequest modifyOpenShipmentRequest);

    /**
     * 
     * @param modifyOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "modifyOpenShipment", action = "http://fedex.com/ws/openship/v18/modifyOpenShipment")
    public Future<?> modifyOpenShipmentAsync(
        @WebParam(name = "ModifyOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentRequest")
        ModifyOpenShipmentRequest modifyOpenShipmentRequest,
        @WebParam(name = "modifyOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ModifyOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param modifyOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/modifyOpenShipment")
    @WebResult(name = "ModifyOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentReply")
    public ModifyOpenShipmentReply modifyOpenShipment(
        @WebParam(name = "ModifyOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ModifyOpenShipmentRequest")
        ModifyOpenShipmentRequest modifyOpenShipmentRequest);

    /**
     * 
     * @param confirmConsolidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ConfirmConsolidationReply>
     */
    @WebMethod(operationName = "confirmConsolidation", action = "http://fedex.com/ws/openship/v18/confirmConsolidation")
    public Response<ConfirmConsolidationReply> confirmConsolidationAsync(
        @WebParam(name = "ConfirmConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationRequest")
        ConfirmConsolidationRequest confirmConsolidationRequest);

    /**
     * 
     * @param asyncHandler
     * @param confirmConsolidationRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "confirmConsolidation", action = "http://fedex.com/ws/openship/v18/confirmConsolidation")
    public Future<?> confirmConsolidationAsync(
        @WebParam(name = "ConfirmConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationRequest")
        ConfirmConsolidationRequest confirmConsolidationRequest,
        @WebParam(name = "confirmConsolidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ConfirmConsolidationReply> asyncHandler);

    /**
     * 
     * @param confirmConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/confirmConsolidation")
    @WebResult(name = "ConfirmConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationReply")
    public ConfirmConsolidationReply confirmConsolidation(
        @WebParam(name = "ConfirmConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ConfirmConsolidationRequest")
        ConfirmConsolidationRequest confirmConsolidationRequest);

    /**
     * 
     * @param createPendingShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.CreateOpenShipmentReply>
     */
    @WebMethod(operationName = "createPendingShipment", action = "http://fedex.com/ws/openship/v18/createPendingShipment")
    public Response<CreateOpenShipmentReply> createPendingShipmentAsync(
        @WebParam(name = "CreatePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentRequest")
        CreateOpenShipmentRequest createPendingShipmentRequest);

    /**
     * 
     * @param asyncHandler
     * @param createPendingShipmentRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createPendingShipment", action = "http://fedex.com/ws/openship/v18/createPendingShipment")
    public Future<?> createPendingShipmentAsync(
        @WebParam(name = "CreatePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentRequest")
        CreateOpenShipmentRequest createPendingShipmentRequest,
        @WebParam(name = "createPendingShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CreateOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param createPendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/createPendingShipment")
    @WebResult(name = "CreatePendingShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentReply")
    public CreateOpenShipmentReply createPendingShipment(
        @WebParam(name = "CreatePendingShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "CreatePendingShipmentRequest")
        CreateOpenShipmentRequest createPendingShipmentRequest);

    /**
     * 
     * @param getModifyOpenShipmentResultsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.GetModifyOpenShipmentResultsReply>
     */
    @WebMethod(operationName = "getModifyOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getModifyOpenShipmentResults")
    public Response<GetModifyOpenShipmentResultsReply> getModifyOpenShipmentResultsAsync(
        @WebParam(name = "GetModifyOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsRequest")
        GetModifyOpenShipmentResultsRequest getModifyOpenShipmentResultsRequest);

    /**
     * 
     * @param getModifyOpenShipmentResultsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getModifyOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getModifyOpenShipmentResults")
    public Future<?> getModifyOpenShipmentResultsAsync(
        @WebParam(name = "GetModifyOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsRequest")
        GetModifyOpenShipmentResultsRequest getModifyOpenShipmentResultsRequest,
        @WebParam(name = "getModifyOpenShipmentResultsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetModifyOpenShipmentResultsReply> asyncHandler);

    /**
     * 
     * @param getModifyOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetModifyOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getModifyOpenShipmentResults")
    @WebResult(name = "GetModifyOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsReply")
    public GetModifyOpenShipmentResultsReply getModifyOpenShipmentResults(
        @WebParam(name = "GetModifyOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetModifyOpenShipmentResultsRequest")
        GetModifyOpenShipmentResultsRequest getModifyOpenShipmentResultsRequest);

    /**
     * 
     * @param deletePackagesFromOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.DeletePackagesFromOpenShipmentReply>
     */
    @WebMethod(operationName = "deletePackagesFromOpenShipment", action = "http://fedex.com/ws/openship/v18/deletePackagesFromOpenShipment")
    public Response<DeletePackagesFromOpenShipmentReply> deletePackagesFromOpenShipmentAsync(
        @WebParam(name = "DeletePackagesFromOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentRequest")
        DeletePackagesFromOpenShipmentRequest deletePackagesFromOpenShipmentRequest);

    /**
     * 
     * @param deletePackagesFromOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deletePackagesFromOpenShipment", action = "http://fedex.com/ws/openship/v18/deletePackagesFromOpenShipment")
    public Future<?> deletePackagesFromOpenShipmentAsync(
        @WebParam(name = "DeletePackagesFromOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentRequest")
        DeletePackagesFromOpenShipmentRequest deletePackagesFromOpenShipmentRequest,
        @WebParam(name = "deletePackagesFromOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeletePackagesFromOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param deletePackagesFromOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePackagesFromOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deletePackagesFromOpenShipment")
    @WebResult(name = "DeletePackagesFromOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentReply")
    public DeletePackagesFromOpenShipmentReply deletePackagesFromOpenShipment(
        @WebParam(name = "DeletePackagesFromOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeletePackagesFromOpenShipmentRequest")
        DeletePackagesFromOpenShipmentRequest deletePackagesFromOpenShipmentRequest);

    /**
     * 
     * @param reprintShippingDocumentsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.ReprintShippingDocumentsReply>
     */
    @WebMethod(operationName = "reprintShippingDocuments", action = "http://fedex.com/ws/openship/v18/reprintShippingDocuments")
    public Response<ReprintShippingDocumentsReply> reprintShippingDocumentsAsync(
        @WebParam(name = "ReprintShippingDocumentsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsRequest")
        ReprintShippingDocumentsRequest reprintShippingDocumentsRequest);

    /**
     * 
     * @param asyncHandler
     * @param reprintShippingDocumentsRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "reprintShippingDocuments", action = "http://fedex.com/ws/openship/v18/reprintShippingDocuments")
    public Future<?> reprintShippingDocumentsAsync(
        @WebParam(name = "ReprintShippingDocumentsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsRequest")
        ReprintShippingDocumentsRequest reprintShippingDocumentsRequest,
        @WebParam(name = "reprintShippingDocumentsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ReprintShippingDocumentsReply> asyncHandler);

    /**
     * 
     * @param reprintShippingDocumentsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ReprintShippingDocumentsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/reprintShippingDocuments")
    @WebResult(name = "ReprintShippingDocumentsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsReply")
    public ReprintShippingDocumentsReply reprintShippingDocuments(
        @WebParam(name = "ReprintShippingDocumentsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "ReprintShippingDocumentsRequest")
        ReprintShippingDocumentsRequest reprintShippingDocumentsRequest);

    /**
     * 
     * @param addPackagesToOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.AddPackagesToOpenShipmentReply>
     */
    @WebMethod(operationName = "addPackagesToOpenShipment", action = "http://fedex.com/ws/openship/v18/addPackagesToOpenShipment")
    public Response<AddPackagesToOpenShipmentReply> addPackagesToOpenShipmentAsync(
        @WebParam(name = "AddPackagesToOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentRequest")
        AddPackagesToOpenShipmentRequest addPackagesToOpenShipmentRequest);

    /**
     * 
     * @param addPackagesToOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "addPackagesToOpenShipment", action = "http://fedex.com/ws/openship/v18/addPackagesToOpenShipment")
    public Future<?> addPackagesToOpenShipmentAsync(
        @WebParam(name = "AddPackagesToOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentRequest")
        AddPackagesToOpenShipmentRequest addPackagesToOpenShipmentRequest,
        @WebParam(name = "addPackagesToOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AddPackagesToOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param addPackagesToOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.AddPackagesToOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/addPackagesToOpenShipment")
    @WebResult(name = "AddPackagesToOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentReply")
    public AddPackagesToOpenShipmentReply addPackagesToOpenShipment(
        @WebParam(name = "AddPackagesToOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "AddPackagesToOpenShipmentRequest")
        AddPackagesToOpenShipmentRequest addPackagesToOpenShipmentRequest);

    /**
     * 
     * @param getCreateOpenShipmentResultsRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.GetCreateOpenShipmentResultsReply>
     */
    @WebMethod(operationName = "getCreateOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getCreateOpenShipmentResults")
    public Response<GetCreateOpenShipmentResultsReply> getCreateOpenShipmentResultsAsync(
        @WebParam(name = "GetCreateOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsRequest")
        GetCreateOpenShipmentResultsRequest getCreateOpenShipmentResultsRequest);

    /**
     * 
     * @param asyncHandler
     * @param getCreateOpenShipmentResultsRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCreateOpenShipmentResults", action = "http://fedex.com/ws/openship/v18/getCreateOpenShipmentResults")
    public Future<?> getCreateOpenShipmentResultsAsync(
        @WebParam(name = "GetCreateOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsRequest")
        GetCreateOpenShipmentResultsRequest getCreateOpenShipmentResultsRequest,
        @WebParam(name = "getCreateOpenShipmentResultsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCreateOpenShipmentResultsReply> asyncHandler);

    /**
     * 
     * @param getCreateOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetCreateOpenShipmentResultsReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/getCreateOpenShipmentResults")
    @WebResult(name = "GetCreateOpenShipmentResultsReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsReply")
    public GetCreateOpenShipmentResultsReply getCreateOpenShipmentResults(
        @WebParam(name = "GetCreateOpenShipmentResultsRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "GetCreateOpenShipmentResultsRequest")
        GetCreateOpenShipmentResultsRequest getCreateOpenShipmentResultsRequest);

    /**
     * 
     * @param retrieveConsolidationRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.RetrieveConsolidationReply>
     */
    @WebMethod(operationName = "retrieveConsolidation", action = "http://fedex.com/ws/openship/v18/retrieveConsolidation")
    public Response<RetrieveConsolidationReply> retrieveConsolidationAsync(
        @WebParam(name = "RetrieveConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationRequest")
        RetrieveConsolidationRequest retrieveConsolidationRequest);

    /**
     * 
     * @param retrieveConsolidationRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "retrieveConsolidation", action = "http://fedex.com/ws/openship/v18/retrieveConsolidation")
    public Future<?> retrieveConsolidationAsync(
        @WebParam(name = "RetrieveConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationRequest")
        RetrieveConsolidationRequest retrieveConsolidationRequest,
        @WebParam(name = "retrieveConsolidationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RetrieveConsolidationReply> asyncHandler);

    /**
     * 
     * @param retrieveConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidationReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/retrieveConsolidation")
    @WebResult(name = "RetrieveConsolidationReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationReply")
    public RetrieveConsolidationReply retrieveConsolidation(
        @WebParam(name = "RetrieveConsolidationRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "RetrieveConsolidationRequest")
        RetrieveConsolidationRequest retrieveConsolidationRequest);

    /**
     * 
     * @param deleteOpenShipmentRequest
     * @return
     *     returns jakarta.xml.ws.Response<com.fedex.ws.openship.v18.DeleteOpenShipmentReply>
     */
    @WebMethod(operationName = "deleteOpenShipment", action = "http://fedex.com/ws/openship/v18/deleteOpenShipment")
    public Response<DeleteOpenShipmentReply> deleteOpenShipmentAsync(
        @WebParam(name = "DeleteOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentRequest")
        DeleteOpenShipmentRequest deleteOpenShipmentRequest);

    /**
     * 
     * @param deleteOpenShipmentRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteOpenShipment", action = "http://fedex.com/ws/openship/v18/deleteOpenShipment")
    public Future<?> deleteOpenShipmentAsync(
        @WebParam(name = "DeleteOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentRequest")
        DeleteOpenShipmentRequest deleteOpenShipmentRequest,
        @WebParam(name = "deleteOpenShipmentResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteOpenShipmentReply> asyncHandler);

    /**
     * 
     * @param deleteOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/openship/v18/deleteOpenShipment")
    @WebResult(name = "DeleteOpenShipmentReply", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentReply")
    public DeleteOpenShipmentReply deleteOpenShipment(
        @WebParam(name = "DeleteOpenShipmentRequest", targetNamespace = "http://fedex.com/ws/openship/v18", partName = "DeleteOpenShipmentRequest")
        DeleteOpenShipmentRequest deleteOpenShipmentRequest);

}
