
package com.fedex.ws.openship.v18;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "OpenShipServicePort", serviceName = "OpenShipService", targetNamespace = "http://fedex.com/ws/openship/v18", wsdlLocation = "ws/fedex/wsdl/OpenshipService_v18.wsdl", endpointInterface = "com.fedex.ws.openship.v18.OpenShipPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class OpenShipService_OpenShipServicePortImpl
    implements OpenShipPortType
{


    public OpenShipService_OpenShipServicePortImpl() {
    }

    /**
     * 
     * @param modifyConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyConsolidationReply
     */
    public ModifyConsolidationReply modifyConsolidation(ModifyConsolidationRequest modifyConsolidationRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param validateOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ValidateOpenShipmentReply
     */
    public ValidateOpenShipmentReply validateOpenShipment(ValidateOpenShipmentRequest validateOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param retrieveOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveOpenShipmentReply
     */
    public RetrieveOpenShipmentReply retrieveOpenShipment(RetrieveOpenShipmentRequest retrieveOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deleteOpenConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenConsolidationReply
     */
    public DeleteOpenConsolidationReply deleteOpenConsolidation(DeleteOpenConsolidationRequest deleteOpenConsolidationRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param createConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateConsolidationReply
     */
    public CreateConsolidationReply createConsolidation(CreateConsolidationRequest createConsolidationRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param retrievePackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrievePackageInOpenShipmentReply
     */
    public RetrievePackageInOpenShipmentReply retrievePackageInOpenShipment(RetrievePackageInOpenShipmentRequest retrievePackageInOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param retrieveConsolidatedCommoditiesRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidatedCommoditiesReply
     */
    public RetrieveConsolidatedCommoditiesReply retrieveConsolidatedCommodities(RetrieveConsolidatedCommoditiesRequest retrieveConsolidatedCommoditiesRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param modifyPackageInOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyPackageInOpenShipmentReply
     */
    public ModifyPackageInOpenShipmentReply modifyPackageInOpenShipment(ModifyPackageInOpenShipmentRequest modifyPackageInOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ShipmentReply
     */
    public ShipmentReply deleteShipment(DeleteShipmentRequest deleteShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param createOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    public CreateOpenShipmentReply createOpenShipment(CreateOpenShipmentRequest createOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deletePendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePendingShipmentReply
     */
    public DeletePendingShipmentReply deletePendingShipment(DeletePendingShipmentRequest deletePendingShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param confirmOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmOpenShipmentReply
     */
    public ConfirmOpenShipmentReply confirmOpenShipment(ConfirmOpenShipmentRequest confirmOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getConfirmOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmOpenShipmentResultsReply
     */
    public GetConfirmOpenShipmentResultsReply getConfirmOpenShipmentResults(GetConfirmOpenShipmentResultsRequest getConfirmOpenShipmentResultsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getConfirmConsolidationResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetConfirmConsolidationResultsReply
     */
    public GetConfirmConsolidationResultsReply getConfirmConsolidationResults(GetConfirmConsolidationResultsRequest getConfirmConsolidationResultsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param modifyOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ModifyOpenShipmentReply
     */
    public ModifyOpenShipmentReply modifyOpenShipment(ModifyOpenShipmentRequest modifyOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param confirmConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ConfirmConsolidationReply
     */
    public ConfirmConsolidationReply confirmConsolidation(ConfirmConsolidationRequest confirmConsolidationRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param createPendingShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.CreateOpenShipmentReply
     */
    public CreateOpenShipmentReply createPendingShipment(CreateOpenShipmentRequest createPendingShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getModifyOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetModifyOpenShipmentResultsReply
     */
    public GetModifyOpenShipmentResultsReply getModifyOpenShipmentResults(GetModifyOpenShipmentResultsRequest getModifyOpenShipmentResultsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deletePackagesFromOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeletePackagesFromOpenShipmentReply
     */
    public DeletePackagesFromOpenShipmentReply deletePackagesFromOpenShipment(DeletePackagesFromOpenShipmentRequest deletePackagesFromOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param reprintShippingDocumentsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.ReprintShippingDocumentsReply
     */
    public ReprintShippingDocumentsReply reprintShippingDocuments(ReprintShippingDocumentsRequest reprintShippingDocumentsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param addPackagesToOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.AddPackagesToOpenShipmentReply
     */
    public AddPackagesToOpenShipmentReply addPackagesToOpenShipment(AddPackagesToOpenShipmentRequest addPackagesToOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param getCreateOpenShipmentResultsRequest
     * @return
     *     returns com.fedex.ws.openship.v18.GetCreateOpenShipmentResultsReply
     */
    public GetCreateOpenShipmentResultsReply getCreateOpenShipmentResults(GetCreateOpenShipmentResultsRequest getCreateOpenShipmentResultsRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param retrieveConsolidationRequest
     * @return
     *     returns com.fedex.ws.openship.v18.RetrieveConsolidationReply
     */
    public RetrieveConsolidationReply retrieveConsolidation(RetrieveConsolidationRequest retrieveConsolidationRequest) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param deleteOpenShipmentRequest
     * @return
     *     returns com.fedex.ws.openship.v18.DeleteOpenShipmentReply
     */
    public DeleteOpenShipmentReply deleteOpenShipment(DeleteOpenShipmentRequest deleteOpenShipmentRequest) {
        //replace with your impl here
        return null;
    }

}
