
package com.ups.wsdl.xoltws.freightrate.v1;

import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateRequest;
import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "FreightRatePort", serviceName = "FreightRateService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0", wsdlLocation = "ws/ups/wsdl/FreightRate.wsdl", endpointInterface = "com.ups.wsdl.xoltws.freightrate.v1.FreightRatePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class FreightRateService_FreightRatePortImpl
    implements FreightRatePortType
{


    public FreightRateService_FreightRatePortImpl() {
    }

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse
     * @throws RateErrorMessage
     */
    public FreightRateResponse processFreightRate(FreightRateRequest body, UPSSecurity upsSecurity)
        throws RateErrorMessage
    {
        //replace with your impl here
        return null;
    }

}
