
package com.ups.wsdl.xoltws.freightrate.v1;

import java.util.concurrent.Future;
import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateRequest;
import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FreightRatePortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.freightrate.v1.ObjectFactory.class
})
public interface FreightRatePortType {


    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns jakarta.xml.ws.Response<com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse>
     */
    @WebMethod(operationName = "ProcessFreightRate", action = "http://onlinetools.ups.com/webservices/FreightRateBinding/v1.0")
    public Response<FreightRateResponse> processFreightRateAsync(
        @WebParam(name = "FreightRateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
        FreightRateRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ProcessFreightRate", action = "http://onlinetools.ups.com/webservices/FreightRateBinding/v1.0")
    public Future<?> processFreightRateAsync(
        @WebParam(name = "FreightRateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
        FreightRateRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity,
        @WebParam(name = "ProcessFreightRateResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<FreightRateResponse> asyncHandler);

    /**
     * 
     * @param upsSecurity
     * @param body
     * @return
     *     returns com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse
     * @throws RateErrorMessage
     */
    @WebMethod(operationName = "ProcessFreightRate", action = "http://onlinetools.ups.com/webservices/FreightRateBinding/v1.0")
    @WebResult(name = "FreightRateResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
    public FreightRateResponse processFreightRate(
        @WebParam(name = "FreightRateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
        FreightRateRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws RateErrorMessage
    ;

}
